# Generated by Django 5.2.14 on 2026-05-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Receipt-delivery email for anonymous payments (typically donations without an account). Falls back to user.email when a user is attached.",
                max_length=254,
            ),
        ),
    ]
