# Generated by Django 5.2.14 on 2026-05-28 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DuesPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. AY 2026–2027", max_length=100, unique=True
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "start_date",
                    models.DateField(help_text="First day of the academic year."),
                ),
                ("due_date", models.DateField(help_text="Payment due by this date.")),
                (
                    "end_date",
                    models.DateField(help_text="Last day of the academic year."),
                ),
                (
                    "dues_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount owed by each obligated member.",
                        max_digits=8,
                    ),
                ),
                (
                    "block_registration_when_unpaid",
                    models.BooleanField(
                        default=False,
                        help_text="Future flag — not currently enforced. When True, the registration view will refuse event registrations from obligated unpaid users.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-start_date",),
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="dues_period",
            field=models.ForeignKey(
                blank=True,
                help_text="The dues cycle this payment satisfies — set for type=DUES.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="payments.duesperiod",
            ),
        ),
        migrations.CreateModel(
            name="DuesReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dues_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="payments.duesperiod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dues_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-sent_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "dues_period", "-sent_at"],
                        name="payments_du_user_id_3312be_idx",
                    )
                ],
            },
        ),
    ]
