# Generated by Django 5.2.14 on 2026-05-29 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_seed_initial_dues_period"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TuitionPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. AY 2026–2027", max_length=100, unique=True
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "start_date",
                    models.DateField(help_text="First day of the academic year."),
                ),
                (
                    "decision_due_date",
                    models.DateField(
                        help_text="By this date students should have committed to pay / pay in installments / skip."
                    ),
                ),
                (
                    "end_date",
                    models.DateField(help_text="Last day of the academic year."),
                ),
                (
                    "tuition_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual tuition owed by an enrolled student.",
                        max_digits=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-start_date",),
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("registration", "Registration"),
                    ("dues", "Dues"),
                    ("donation", "Donation"),
                    ("tuition", "Tuition"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TuitionEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("committed", "Committed (will pay)"),
                            ("payment_plan", "On payment plan"),
                            ("paid_in_full", "Paid in full"),
                            ("exempt", "Exempt (staff-applied)"),
                            ("skipping", "Skipping this year"),
                        ],
                        max_length=20,
                    ),
                ),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Staff notes — overrides, special arrangements.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tuition_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tuition_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="payments.tuitionperiod",
                    ),
                ),
            ],
            options={
                "ordering": ("-tuition_period__start_date", "user__last_name"),
            },
        ),
        migrations.CreateModel(
            name="TuitionInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        help_text="1-indexed order within the plan."
                    ),
                ),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="payments.tuitionenrollment",
                    ),
                ),
            ],
            options={
                "ordering": ("enrollment", "sequence"),
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="tuition_installment",
            field=models.ForeignKey(
                blank=True,
                help_text="The tuition installment this payment satisfies — set for type=TUITION.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="payments.tuitioninstallment",
            ),
        ),
        migrations.CreateModel(
            name="TuitionReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tuition_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="payments.tuitionperiod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tuition_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-sent_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="tuitioninstallment",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "sequence"),
                name="payments_unique_installment_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="tuitionenrollment",
            constraint=models.UniqueConstraint(
                fields=("user", "tuition_period"),
                name="payments_unique_user_per_tuition_period",
            ),
        ),
        migrations.AddIndex(
            model_name="tuitionreminder",
            index=models.Index(
                fields=["user", "tuition_period", "-sent_at"],
                name="payments_tu_user_id_0460e7_idx",
            ),
        ),
    ]
