# Generated by Django 5.2.14 on 2026-05-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_dues_tier_amounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="duesperiod",
            name="reminder_interval_days",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="How often to email reminders to unpaid members after the due date.",
            ),
        ),
        migrations.AddField(
            model_name="tuitionperiod",
            name="reminder_interval_days",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="How often to email reminders to students with no decision / unpaid committed status, after the decision-due date.",
            ),
        ),
    ]
