# Generated by Django 5.2.14 on 2026-06-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_drop_exempt_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="source",
            field=models.CharField(
                choices=[
                    ("verified", "Verified against records"),
                    ("imported", "Imported from treasurer ledger"),
                    ("self_reported", "Member-reported (survey)"),
                    ("assumed", "Assumed"),
                    ("staff", "Entered by staff"),
                ],
                db_index=True,
                default="staff",
                help_text="Provenance — how this record entered the system.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tuitionenrollment",
            name="source",
            field=models.CharField(
                choices=[
                    ("verified", "Verified against records"),
                    ("imported", "Imported from treasurer ledger"),
                    ("self_reported", "Member-reported (survey)"),
                    ("assumed", "Assumed"),
                    ("staff", "Entered by staff"),
                ],
                db_index=True,
                default="staff",
                help_text="Provenance — how this enrollment record entered the system.",
                max_length=20,
            ),
        ),
    ]
