# Generated by Django 5.2.14 on 2026-06-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_backfill_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="livemode",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="False for Stripe *test*-mode payments — kept out of real accounting. Offline/manual and live payments are True.",
            ),
        ),
    ]
