# Generated by Django 5.2.14 on 2026-06-04 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_payment_livemode"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="member_note",
            field=models.TextField(
                blank=True,
                help_text="A note the member wrote about this payment (visible to the treasurer).",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="tuition_period",
            field=models.ForeignKey(
                blank=True,
                help_text="The academic year a tuition payment is for, when assigned directly (overrides the date-based attribution; e.g. an August payment the member assigns to a specific AY).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="payments.tuitionperiod",
            ),
        ),
    ]
