# Generated by Django 5.2.14 on 2026-07-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_payment_member_note_payment_tuition_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='source',
            field=models.CharField(choices=[('verified', 'Verified against records'), ('imported', 'Imported from treasurer ledger'), ('stripe', 'Imported from Stripe'), ('self_reported', 'Member-reported (survey)'), ('assumed', 'Assumed'), ('staff', 'Entered by staff')], db_index=True, default='staff', help_text='Provenance — how this record entered the system.', max_length=20),
        ),
        migrations.AlterField(
            model_name='tuitionenrollment',
            name='source',
            field=models.CharField(choices=[('verified', 'Verified against records'), ('imported', 'Imported from treasurer ledger'), ('stripe', 'Imported from Stripe'), ('self_reported', 'Member-reported (survey)'), ('assumed', 'Assumed'), ('staff', 'Entered by staff')], db_index=True, default='staff', help_text='Provenance — how this enrollment record entered the system.', max_length=20),
        ),
    ]
