# Generated by Django 5.2.14 on 2026-07-15 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_reclassify_stripe_import_sources'),
        ('registrations', '0004_remove_registration_registrations_one_active_per_user_event_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('dues', 'Dues'), ('tuition', 'Tuition'), ('registration', 'Registration')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('effective_date', models.DateField(help_text='Orders the oldest-first coverage sweep — AY start for dues/tuition, settle date for registrations.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('waived', 'Waived'), ('void', 'Void')], db_index=True, default='open', max_length=10)),
                ('source', models.CharField(choices=[('verified', 'Verified against records'), ('imported', 'Imported from treasurer ledger'), ('stripe', 'Imported from Stripe'), ('self_reported', 'Member-reported (survey)'), ('assumed', 'Assumed'), ('staff', 'Entered by staff')], db_index=True, default='staff', help_text='Provenance — how this charge entered the system.', max_length=20)),
                ('staff_adjusted', models.BooleanField(default=False, help_text='Set when a treasurer edits this row; the minting syncs then never touch it (disagreements surface on the Reconcile tab).')),
                ('notes', models.TextField(blank=True, help_text='Append-only audit trail.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dues_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='payments.duesperiod')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='registrations.registration')),
                ('tuition_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='payments.tuitionperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('effective_date', 'id'),
                'indexes': [models.Index(fields=['user', 'status'], name='payments_ch_user_id_e6863d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dues_period__isnull', False), models.Q(('status', 'void'), _negated=True)), fields=('user', 'dues_period'), name='charge_unique_user_dues_period'), models.UniqueConstraint(condition=models.Q(('tuition_period__isnull', False), models.Q(('status', 'void'), _negated=True)), fields=('user', 'tuition_period'), name='charge_unique_user_tuition_period'), models.UniqueConstraint(condition=models.Q(('registration__isnull', False), models.Q(('status', 'void'), _negated=True)), fields=('registration',), name='charge_unique_registration')],
            },
        ),
    ]
