# Generated by Django 5.2.14 on 2026-07-16 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='split_from',
            field=models.ForeignKey(blank=True, help_text='Set on the sibling rows created when a payment is split across categories; the parent row keeps the Stripe identifiers and the receipt. Refunding any part refunds the whole original charge.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='split_parts', to='payments.payment'),
        ),
    ]
