# Generated by Django 5.2.14 on 2026-07-16 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_payment_split_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payment', 'Payment (I paid this)'), ('charge', 'Charge (I owed this)')], max_length=10)),
                ('category', models.CharField(choices=[('registration', 'Registration'), ('dues', 'Dues'), ('donation', 'Donation'), ('tuition', 'Tuition')], help_text='Payment.Type values for a payment claim; dues/tuition/registration (Charge.Category) for a charge claim.', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('claimed_date', models.DateField(help_text='When the member says this happened.')),
                ('details', models.TextField(help_text="The member's account of what this was.")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], db_index=True, default='pending', max_length=10)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.charge')),
                ('created_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.payment')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_submissions_decided', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
