# Generated by Django 5.2.14 on 2026-07-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_paymentmemberaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionperiod',
            name='payment_due_date',
            field=models.DateField(blank=True, help_text='Tuition payment due by this date (unpaid-committed reminders escalate after it; decision reminders key off decision_due_date).', null=True),
        ),
    ]
