# Generated by Django 5.2.14 on 2026-07-23 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_tuitionperiod_payment_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionenrollment',
            name='status',
            field=models.CharField(choices=[('committed', 'Committed (will pay)'), ('payment_plan', 'On payment plan'), ('paid_in_full', 'Paid in full'), ('skipping', 'Skipping this year'), ('plan_requested', 'Payment plan requested')], max_length=20),
        ),
        migrations.CreateModel(
            name='TuitionPlanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons', models.TextField(help_text="The student's stated reasons for requesting a payment plan.")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text="Board's decision note, if any.")),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tuition_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_applications', to='payments.tuitionperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_plan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'tuition_period'), name='one_pending_plan_application')],
            },
        ),
    ]
