# Generated by Django 5.2.14 on 2026-08-03 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_payment_abandoned_status'),
        ('registrations', '0004_remove_registration_registrations_one_active_per_user_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(help_text='1-indexed order within the plan.')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='registrations.registration')),
            ],
            options={
                'ordering': ('registration', 'sequence'),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='registration_installment',
            field=models.ForeignKey(blank=True, help_text='The registration installment this payment satisfies — set for a payment-plan registration (task #501).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.registrationinstallment'),
        ),
        migrations.AddConstraint(
            model_name='registrationinstallment',
            constraint=models.UniqueConstraint(fields=('registration', 'sequence'), name='payments_unique_registration_installment_sequence'),
        ),
    ]
