# Generated by Django 5.2.14 on 2026-05-27 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Editable by faculty for events they teach (PROG-7).",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("seminar", "Seminar"),
                            ("special_event", "Special event"),
                        ],
                        default="seminar",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("in_person", "In person"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                (
                    "access_info",
                    models.TextField(
                        blank=True,
                        help_text="Zoom link or similar. Released to registrants only after payment (REG-8).",
                    ),
                ),
                ("registration_opens", models.DateTimeField(blank=True, null=True)),
                ("registration_closes", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open for registration"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the public event page is visible (PROG-1).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "faculty",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Instructors. Restricted to users marked is_faculty (USR-6).",
                        limit_choices_to={"profile__is_faculty": True},
                        related_name="events_taught",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-start_date", "title"),
            },
        ),
        migrations.CreateModel(
            name="PricingCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "pricing_mode",
                    models.CharField(
                        choices=[
                            ("percent_off", "Percent off"),
                            ("fixed_amount", "Fixed amount"),
                            ("sliding_floor", "Sliding-scale floor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount_or_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Interpreted per pricing_mode: percent_off → 0–100 (percent), fixed_amount → USD price, sliding_floor → USD minimum.",
                        max_digits=8,
                    ),
                ),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True, help_text="Null = unlimited.", null=True
                    ),
                ),
                (
                    "uses_remaining",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Decremented on successful redemption. Null when max_uses is null.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_codes",
                        to="events.event",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        help_text="Faculty member who minted the code.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pricing_codes_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restricted_to_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="When set, only that user can redeem.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pricing_codes_eligible",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Room name or address for in-person/hybrid sessions.",
                        max_length=200,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=0, help_text="Stable ordering within an event."
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ("event", "sequence", "start_at"),
            },
        ),
        migrations.CreateModel(
            name="PriceTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("prospective_applicant", "Prospective applicant"),
                            ("student", "Student"),
                            ("pre_candidate", "Pre-candidate"),
                            ("candidate", "Candidate"),
                            ("analyst", "Analyst"),
                            ("member", "Member"),
                            ("external", "External / non-LSP"),
                        ],
                        default="all",
                        max_length=32,
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Listed price in USD.", max_digits=8
                    ),
                ),
                (
                    "sliding_scale",
                    models.BooleanField(
                        default=False,
                        help_text="If true, the payer may choose any amount at or above minimum_amount (REG-5).",
                    ),
                ),
                (
                    "minimum_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Floor for sliding-scale tiers; 0 expresses 'none turned away'.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "covered_by_tuition",
                    models.BooleanField(
                        default=False,
                        help_text="Tuition-paying members in this audience owe nothing (REG-4).",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_tiers",
                        to="events.event",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set only for per-class pricing (REG-6).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_tiers",
                        to="events.session",
                    ),
                ),
            ],
            options={
                "ordering": ("event", "session", "audience"),
            },
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["start_at"], name="events_sess_start_a_d6b71d_idx"
            ),
        ),
    ]
