# Generated by Django 5.2.14 on 2026-05-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingcode",
            name="amount_or_percent",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Interpreted per pricing_mode: percent_off → 0–100 (percent), fixed_amount → USD price, sliding_floor → USD minimum the participant must meet or exceed.",
                max_digits=8,
            ),
        ),
    ]
