# Generated by Django 5.2.14 on 2026-05-28 04:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_pricingcode_amount_or_percent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "affiliation",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Dublin City University'.",
                        max_length=200,
                    ),
                ),
                (
                    "headshot",
                    models.ImageField(blank=True, null=True, upload_to="speakers/%Y/"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email — not a login. Optional, staff-visible.",
                        max_length=254,
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to show this speaker on public event pages.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="faculty",
            field=models.ManyToManyField(
                blank=True,
                help_text="LSP-affiliated instructors (User accounts). Restricted to is_faculty (USR-6).",
                limit_choices_to={"profile__is_faculty": True},
                related_name="events_taught",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pricetier",
            name="audience",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("prospective_applicant", "Prospective applicant"),
                    ("student", "Student"),
                    ("pre_candidate", "Pre-candidate"),
                    ("candidate", "Candidate"),
                    ("analyst", "Analyst"),
                    ("member", "Member"),
                    ("external", "Guest"),
                ],
                default="all",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="speakers",
            field=models.ManyToManyField(
                blank=True,
                help_text="External presenters with no LSP account. Use for guest speakers; for LSP faculty teaching this event, use the ``faculty`` field instead.",
                related_name="events",
                to="events.speaker",
            ),
        ),
    ]
