# Generated by Django 5.2.14 on 2026-05-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0003_speaker_alter_event_faculty_alter_pricetier_audience_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricetier",
            name="audience",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("prospective_applicant", "Prospective applicant"),
                    ("student", "Student"),
                    ("pre_candidate", "Pre-candidate analyst"),
                    ("candidate", "Candidate analyst"),
                    ("analyst", "Analyst"),
                    ("pre_candidate_scholar", "Pre-candidate scholar"),
                    ("candidate_scholar", "Candidate scholar"),
                    ("scholar", "Scholar"),
                    ("member", "Member"),
                    ("external", "Guest"),
                ],
                default="all",
                max_length=32,
            ),
        ),
    ]
