# Generated by Django 5.2.14 on 2026-05-28 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_pricetier_audience"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="speakers",
            field=models.ManyToManyField(
                blank=True,
                help_text="External presenters with no LSP account. For LSP-affiliated presenters with a User account, use ``member_speakers`` instead so we don't duplicate their bio/headshot. For instructors who should be able to edit the event, use ``faculty``.",
                related_name="events",
                to="events.speaker",
            ),
        ),
        migrations.CreateModel(
            name="EventMemberSpeaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio_override",
                    models.TextField(
                        blank=True,
                        help_text="Optional per-event bio. Falls back to Profile.bio when blank.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first. Ties break on name.",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "user__last_name", "user__first_name"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="member_speakers",
            field=models.ManyToManyField(
                blank=True,
                help_text="LSP-affiliated presenters (User accounts). Bio defaults to Profile.bio but can be overridden per-event via the EventMemberSpeaker through model. Display-only — does not grant edit access.",
                related_name="speaking_engagements",
                through="events.EventMemberSpeaker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="eventmemberspeaker",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="event_member_speaker_unique"
            ),
        ),
    ]
