# Generated by Django 5.2.14 on 2026-05-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_remove_eventmemberspeaker_bio_override"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("seminar", "Seminar"),
                    ("special_event", "Special event"),
                    ("reading_group", "Reading group"),
                    ("cartel", "Cartel"),
                ],
                default="seminar",
                max_length=20,
            ),
        ),
    ]
