# Generated by Django 5.2.14 on 2026-05-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_alter_event_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("members_only", "Members only")],
                default="public",
                help_text="Members-only events (e.g. Scholarly Seminar Series) are hidden from anonymous visitors on public listings.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("seminar", "Seminar"),
                    ("reading_group", "Reading group"),
                    ("cartel", "Cartel"),
                    ("special_event", "Special event"),
                    ("day_of_assembly", "Day of Assembly"),
                    ("working_day", "Working Day"),
                    ("scholarly_seminar", "Scholarly Seminar Series"),
                ],
                default="seminar",
                max_length=20,
            ),
        ),
    ]
