# Generated by Django 5.2.14 on 2026-05-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_event_visibility_alter_event_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricetier",
            name="covered_by_tuition",
            field=models.BooleanField(
                default=False,
                help_text="If set, tuition-current members in this tier's audience get this event for free (REG-4). Whether a given event is tuition-covered is decided here, per-event: a special event with no covered_by_tuition tier charges tuition-paying members the standard tier amount.",
            ),
        ),
    ]
