# Generated by Django 5.2.14 on 2026-05-30 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_pricetier_covered_by_tuition"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        help_text="e.g. '2026-2027'.", max_length=20, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional display name; defaults to 'Program {academic_year}'.",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional intro shown on /program/?year=... when published.",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="If True, the program and its events are publicly visible on /program/ and /events/. If False, only Program Committee members and staff can preview.",
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="If set and in the past, the program is treated as published — use this to schedule a program release for a future moment.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-academic_year",),
            },
        ),
        migrations.AddField(
            model_name="event",
            name="program",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for annual-program-type events (seminar, reading group, cartel) — links the event to its academic-year Program. Drives public visibility via Program.is_public_now.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="events.program",
            ),
        ),
    ]
