# Generated by Django 5.2.14 on 2026-05-31 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_program_backfill"),
        ("workgroups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="workgroup",
            field=models.OneToOneField(
                blank=True,
                help_text="Optional collaborative workspace (channel + shared files) for this event's participants. Roster derives from faculty + paid/comped registrants — not hand-managed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event",
                to="workgroups.workgroup",
            ),
        ),
    ]
