# Generated by Django 5.2.14 on 2026-05-31 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_event_workgroup"),
        ("workgroups", "0002_alter_workgroup_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="workgroup",
            field=models.ForeignKey(
                blank=True,
                help_text="The workgroup that generates/owns this event (Workgroup-primary model — see docs/design-workgroup-events.md). For offerings it's the offering's own group; for special events it's the organizing committee. A group may generate many events over time.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="workgroups.workgroup",
            ),
        ),
    ]
