"""R2 — backfill: every existing Event gets a generating Workgroup.

Workgroup-primary reframe (docs/design-workgroup-events.md):
- Annual-program offerings (seminar / reading_group / cartel) each get a
  freshly created offering Workgroup of the matching kind, plus its discussion
  channel (the auto-provision signal does NOT fire for historical-model
  creates, so we create the channel explicitly — as in the committee fold-in).
  One Workgroup per Event (no cross-year merge — locked decision #1).
- Special events / Days of Assembly / Working Days / Scholarly Seminars are
  generated by the Programming Committee → linked to the PC's workgroup (no new
  channel; the PC already has one).

Reverse = noop.
"""

from django.db import migrations

OFFERING_KINDS = {
    "seminar": "seminar",
    "reading_group": "reading_group",
    "cartel": "cartel",
}
PC_OWNED_TYPES = {"special_event", "day_of_assembly", "working_day", "scholarly_seminar"}

#: capability-toggle seed per offering kind (mirrors Workgroup.KIND_TOGGLE_DEFAULTS).
TOGGLE_SEED = {
    "seminar": {"has_works": False, "has_calendar": True},
    "reading_group": {"has_calendar": True},
    "cartel": {"has_calendar": True, "has_tasks": True},
}
#: channel category (name, position) per offering kind.
CATEGORY = {
    "seminar": ("Seminars", 50),
    "reading_group": ("Reading Groups", 35),
    "cartel": ("Cartels", 30),
}


def _unique(model, field, base, cap):
    base = (base or "x")[:cap - 6]  # leave room for a "-NNN" disambiguator
    value, n = base, 2
    while model.objects.filter(**{field: value}).exists():
        value = f"{base}-{n}"
        n += 1
    return value


def backfill(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Workgroup = apps.get_model("workgroups", "Workgroup")
    Channel = apps.get_model("parletre", "Channel")
    ChannelCategory = apps.get_model("parletre", "ChannelCategory")
    Committee = apps.get_model("committees", "Committee")

    pc = Committee.objects.filter(slug="programming-committee").first()
    pc_wg_id = pc.workgroup_id if pc else None

    cats = {}
    offerings = pc_linked = skipped = 0

    for event in Event.objects.filter(workgroup__isnull=True):
        kind = OFFERING_KINDS.get(event.event_type)
        if kind:
            wg = Workgroup.objects.create(
                kind=kind,
                name=event.title[:120],   # Workgroup.name is max_length=120; Event.title is 200
                slug=_unique(Workgroup, "slug", event.slug, 140),
                description=event.description or "",
                landing_visibility="members",
                content_visibility="private",
                **TOGGLE_SEED.get(kind, {}),
            )
            if kind not in cats:
                cname, cpos = CATEGORY[kind]
                cats[kind], _ = ChannelCategory.objects.get_or_create(
                    name=cname, defaults={"slug": cname.lower().replace(" ", "-"), "position": cpos}
                )
            Channel.objects.create(
                name=event.title[:120],   # Channel.name is max_length=120
                slug=_unique(Channel, "slug", event.slug, 110),
                kind="forum",
                access="workgroup",
                workgroup=wg,
                category=cats[kind],
                description=f"Discussion for {event.title}.",
            )
            event.workgroup = wg
            event.save(update_fields=["workgroup"])
            offerings += 1
        elif event.event_type in PC_OWNED_TYPES and pc_wg_id:
            event.workgroup_id = pc_wg_id
            event.save(update_fields=["workgroup"])
            pc_linked += 1
        else:
            skipped += 1

    print(
        f"  R2 backfill: {offerings} offering workgroups created, "
        f"{pc_linked} linked to PC, {skipped} skipped (unknown type or no PC)."
    )


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_alter_event_workgroup"),
        ("workgroups", "0001_initial"),
        ("committees", "0006_foldin_committees"),
        ("parletre", "0011_alter_channel_access"),
    ]

    operations = [
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
