# Generated by Django 5.2.14 on 2026-06-01 02:19

from django.db import migrations, models
from django.utils import timezone


def backfill_faculty_memberships(apps, schema_editor):
    """Move each Event's faculty (M2M) onto its workgroup as a FACULTY role,
    before the M2M field is dropped. Every Event already has a workgroup
    (migration 0015). Idempotent; copies zero rows if no faculty were set."""
    Event = apps.get_model("events", "Event")
    WorkgroupMembership = apps.get_model("workgroups", "WorkgroupMembership")
    today = timezone.now().date()

    for event in Event.objects.exclude(workgroup__isnull=True).prefetch_related("faculty"):
        for user in event.faculty.all():
            existing = WorkgroupMembership.objects.filter(
                workgroup_id=event.workgroup_id, user_id=user.pk, end_date__isnull=True
            ).first()
            if existing is None:
                WorkgroupMembership.objects.create(
                    workgroup_id=event.workgroup_id, user_id=user.pk,
                    role="faculty", start_date=today,
                )
            elif existing.role == "member":
                # Promote a plain membership to faculty.
                existing.role = "faculty"
                existing.save(update_fields=["role"])


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_backfill_event_workgroups"),
        ("workgroups", "0006_alter_workgroupmembership_role"),
    ]

    operations = [
        migrations.RunPython(backfill_faculty_memberships, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="event",
            name="faculty",
        ),
        migrations.AlterField(
            model_name="event",
            name="speakers",
            field=models.ManyToManyField(
                blank=True,
                help_text="External presenters with no LSP account. For LSP-affiliated presenters with a User account, use ``member_speakers`` instead so we don't duplicate their bio/headshot. For instructors who should be able to edit the event, add them as faculty (a role on the event's workgroup).",
                related_name="events",
                to="events.speaker",
            ),
        ),
    ]
