# Generated by Django 5.2.14 on 2026-06-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_remove_event_faculty_alter_event_speakers"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="requires_faculty_approval",
            field=models.BooleanField(
                default=False,
                help_text="If set, each registration must be approved by the event's faculty before it's confirmed (future proposal-flow option). Default off; all existing seminars are off.",
            ),
        ),
    ]
