# Generated by Django 5.2.14 on 2026-06-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_event_requires_faculty_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricetier",
            name="audience",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("prospective_applicant", "Prospective Applicant"),
                    ("student", "Student"),
                    ("pre_candidate", "Pre-Candidate Analyst"),
                    ("candidate", "Candidate Analyst"),
                    ("analyst", "Analyst"),
                    ("pre_candidate_scholar", "Pre-Candidate Scholar"),
                    ("candidate_scholar", "Candidate Scholar"),
                    ("scholar", "Scholar"),
                    ("member", "Member"),
                    ("external", "Auditor"),
                ],
                default="all",
                max_length=32,
            ),
        ),
    ]
