# Generated by Django 5.2.14 on 2026-06-01 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_alter_pricetier_audience"),
        ("workgroups", "0013_workgroup_archived_at_workgroup_archived_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SeminarProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("in_person", "In person"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed — under review"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                        ],
                        default="proposed",
                        max_length=12,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_note",
                    models.TextField(
                        blank=True, help_text="Decline reason / review notes."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "continues_seminar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: propose a new yearly term of this existing seminar.",
                        limit_choices_to={"kind": "seminar"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seminar_proposals",
                        to="workgroups.workgroup",
                    ),
                ),
                (
                    "faculty",
                    models.ManyToManyField(
                        blank=True,
                        related_name="proposed_seminars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "minted_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="from_proposal",
                        to="events.event",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seminar_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seminar_proposals_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
