# Generated by Django 5.2.14 on 2026-06-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_seminarproposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="record_video",
            field=models.BooleanField(
                default=False,
                help_text="Automatically record this event's online meeting (a host's browser starts the recording on join). Off by default; recordings are stored privately and shown per their visibility setting.",
            ),
        ),
    ]
