# Generated by Django 5.2.14 on 2026-06-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_event_record_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="recording_mode",
            field=models.CharField(
                choices=[
                    ("on_demand", "On demand — hosts can record"),
                    ("off", "Off — no Record button"),
                ],
                default="on_demand",
                help_text="Whether hosts see a Record button in this event's own meeting room. Only applies to one-off events (special events, Days of Assembly, Working Days, Scholarly Seminars), which get their own room.",
                max_length=12,
            ),
        ),
    ]
