# Generated by Django 5.2.14 on 2026-06-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_clear_masochism_access_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="seminarproposal",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("seminar", "Seminar"),
                    ("reading_group", "Reading group"),
                    ("special_event", "Special event"),
                ],
                default="seminar",
                help_text="What kind of event you're proposing.",
                max_length=20,
            ),
        ),
    ]
