# Generated by Django 5.2.14 on 2026-06-06 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0023_seminarproposal_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="seminarproposal",
            name="biography",
            field=models.TextField(
                blank=True, help_text="Instructor/convener biography."
            ),
        ),
        migrations.AddField(
            model_name="seminarproposal",
            name="contact",
            field=models.CharField(
                blank=True, help_text="Contact email for this proposal.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="seminarproposal",
            name="date_tbd",
            field=models.BooleanField(
                default=False, help_text="Check if the date/time is not yet decided."
            ),
        ),
        migrations.AddField(
            model_name="seminarproposal",
            name="external_speakers",
            field=models.TextField(
                blank=True,
                help_text="External (non-LSP) speakers: name, affiliation, contact email, and a short bio for each.",
            ),
        ),
        migrations.AddField(
            model_name="seminarproposal",
            name="fee_note",
            field=models.TextField(
                blank=True,
                help_text="Proposed fee, or donation language (e.g. “$100 donation encouraged, none turned away”).",
            ),
        ),
        migrations.AddField(
            model_name="seminarproposal",
            name="honoraria_estimate",
            field=models.CharField(
                blank=True,
                help_text="Estimated speaker honoraria, if any.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="seminarproposal",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Proposed venue (in-person) or platform note.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="seminarproposal",
            name="offers_ce",
            field=models.BooleanField(
                default=False,
                help_text="Offer APA CE credits (you apply to GPPA separately).",
            ),
        ),
        migrations.AddField(
            model_name="seminarproposal",
            name="proposed_time",
            field=models.CharField(
                blank=True,
                help_text="Proposed time (if a date is set).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="seminarproposal",
            name="speaker_arrangement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("proposer", "I'll arrange with the speaker(s) directly"),
                    ("pc", "I'd like the Programming Committee to arrange it"),
                ],
                help_text="Who contacts/arranges with the speakers.",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="access_info",
            field=models.TextField(
                blank=True,
                help_text="Venue/room, dial-in, or an external meeting link. Released to registrants only after payment (REG-8). Leave blank if using the in-site meeting room — registrants get a Join button automatically.",
            ),
        ),
        migrations.AlterField(
            model_name="seminarproposal",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="seminarproposal",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ProposalReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("citation", models.TextField()),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="events.seminarproposal",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
