# Generated by Django 5.2.14 on 2026-06-06 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0025_rename_seminarproposal_eventproposal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventproposal",
            name="biography",
        ),
        migrations.RemoveField(
            model_name="eventproposal",
            name="external_speakers",
        ),
        migrations.RemoveField(
            model_name="eventproposal",
            name="fee_note",
        ),
        migrations.RemoveField(
            model_name="eventproposal",
            name="format",
        ),
        migrations.RemoveField(
            model_name="eventproposal",
            name="proposed_time",
        ),
        migrations.AddField(
            model_name="eventproposal",
            name="fee_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Flat fee in USD. Leave blank for free / sliding-scale.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventproposal",
            name="fee_sliding_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sliding-scale ceiling / suggested amount.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventproposal",
            name="fee_sliding_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sliding-scale floor (0 = none turned away).",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventproposal",
            name="location_kind",
            field=models.CharField(
                choices=[
                    ("online_insite", "Online — in-site video room"),
                    ("online_external", "Online — external platform (Zoom, etc.)"),
                    ("in_person", "In person"),
                    ("hybrid", "Hybrid (in person + online)"),
                ],
                default="online_insite",
                help_text="Where it meets.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eventproposal",
            name="proposed_datetime",
            field=models.DateTimeField(
                blank=True, help_text="Proposed date & time (Pacific).", null=True
            ),
        ),
        migrations.AddField(
            model_name="eventproposal",
            name="tuition_covers",
            field=models.BooleanField(
                default=True,
                help_text="Tuition-current members attend at no charge. Always on for seminars and reading groups.",
            ),
        ),
        migrations.AlterField(
            model_name="eventproposal",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Venue address (in person) or meeting link (external online). Leave blank for the in-site video room.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="eventproposal",
            name="speaker_arrangement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("proposer", "I'll arrange with the speaker(s) directly"),
                    ("pc", "I'd like the Programming Committee to arrange it"),
                ],
                default="proposer",
                help_text="Who contacts/arranges with the speakers.",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="ProposalSpeaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("affiliation", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal_speakers",
                        to="events.eventproposal",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
