# Generated by Django 5.2.14 on 2026-06-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0026_remove_eventproposal_biography_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventproposal",
            name="date_tbd",
            field=models.BooleanField(
                default=False,
                help_text="Check if the date/time is TBD (not yet decided).",
            ),
        ),
        migrations.AlterField(
            model_name="eventproposal",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Venue address (in person or hybrid). Leave blank when online.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="eventproposal",
            name="location_kind",
            field=models.CharField(
                choices=[
                    ("online_insite", "Online — in-site video room"),
                    ("in_person", "In person"),
                    ("hybrid", "Hybrid (in person + online)"),
                ],
                default="online_insite",
                help_text="Where it meets.",
                max_length=20,
            ),
        ),
    ]
