# Generated by Django 5.2.14 on 2026-06-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0027_alter_eventproposal_date_tbd_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventproposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("saved", "Saved — not yet submitted"),
                    ("proposed", "Proposed — under review"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                ],
                default="proposed",
                max_length=12,
            ),
        ),
    ]
