# Generated by Django 5.2.14 on 2026-06-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0028_alter_eventproposal_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventproposal",
            name="sched_access_info",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="eventproposal",
            name="sched_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventproposal",
            name="sched_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekly", "Weekly"),
                    ("biweekly", "Every 2 weeks"),
                    ("monthly", "Monthly (nth weekday)"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="eventproposal",
            name="sched_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="eventproposal",
            name="sched_online_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="eventproposal",
            name="sched_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventproposal",
            name="sched_week_position",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventproposal",
            name="sched_weekdays",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="eventproposal",
            name="schedule_tbd",
            field=models.BooleanField(
                default=True,
                help_text="Schedule the recurring meetings now, or leave TBD.",
            ),
        ),
    ]
