# Generated by Django 5.2.14 on 2026-06-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0029_eventproposal_sched_access_info_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventproposal",
            name="sched_access_info",
        ),
        migrations.RemoveField(
            model_name="eventproposal",
            name="sched_online_url",
        ),
        migrations.RemoveField(
            model_name="eventproposal",
            name="sched_week_position",
        ),
        migrations.AddField(
            model_name="eventproposal",
            name="sched_week_positions",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
