# Generated by Django 5.2.14 on 2026-06-07 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0030_remove_eventproposal_sched_access_info_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventproposal",
            name="sched_location",
        ),
    ]
