# Generated by Django 5.2.14 on 2026-06-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_remove_eventproposal_sched_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.CharField(blank=True, help_text='Public contact for questions about the event (email/phone).', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='fee_note',
            field=models.TextField(blank=True, help_text="Fee in the faculty's own words ('$100 donation encouraged, none turned away'). Shown with the pricing table — the table drives checkout; this preserves the human phrasing."),
        ),
        migrations.AddField(
            model_name='event',
            name='readings',
            field=models.TextField(blank=True, help_text='Reading list, one citation per line (notes and sub-headings may be lines too). Rendered as a formatted list on the event page.'),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule_note',
            field=models.TextField(blank=True, help_text="Human-readable meeting cadence ('1st and 3rd Saturdays, 9–11:30am Pacific'). Shown alongside the sessions table — keeps the faculty's own phrasing even once sessions are generated."),
        ),
    ]
