# Generated by Django 5.2.14 on 2026-06-16 07:54

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_event_contact_event_fee_note_event_readings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text="e.g. '2008-2009' or '1994'.", max_length=20, unique=True)),
                ('label', models.CharField(blank=True, help_text='Optional display label; defaults to the academic year.', max_length=120)),
                ('file', models.FileField(storage=core.storage.private_storage, upload_to='program-archive/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-academic_year',),
            },
        ),
    ]
