# Generated by Django 5.2.14 on 2026-06-23 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_archivedprogram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('self_certified', 'Self-certified minor'), ('administrative', 'Administrative change'), ('pending', 'Pending committee review'), ('approved', 'Approved'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('changed_fields', models.JSONField(default=list)),
                ('description_change_ratio', models.FloatField(default=0.0)),
                ('proposed_title', models.CharField(blank=True, max_length=200)),
                ('proposed_description', models.TextField(blank=True)),
                ('proposed_readings', models.TextField(blank=True)),
                ('proposed_fee_note', models.TextField(blank=True)),
                ('original_title', models.CharField(blank=True, max_length=200)),
                ('original_description', models.TextField(blank=True)),
                ('original_readings', models.TextField(blank=True)),
                ('original_fee_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='events.event')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_changes_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
