# Generated by Django 5.2.14 on 2026-07-24 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_eventchangerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='user',
            field=models.OneToOneField(blank=True, help_text="Optional login for this external presenter (task #463). Linking a user lets them join the meeting and see the event's presenter view, scoped to events they present. Leave blank for display-only speakers.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_speaker', to=settings.AUTH_USER_MODEL),
        ),
    ]
