# Generated by Django 5.2.14 on 2026-07-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_speakerinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='speaker_spotlight',
            field=models.BooleanField(default=False, help_text="Speaker spotlight (task #463): attendees join the online meeting with mic and camera off, so the speaker is the focus. It's a soft spotlight, attendees can still turn them back on, and hosts can mute. Off by default; suited to a talk or lecture."),
        ),
    ]
