# Generated by Django 5.2.14 on 2026-07-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_event_speaker_spotlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='open_to_guests',
            field=models.BooleanField(default=True, help_text='Non-members are welcome to register for this event. Shows a guests-welcome note on the event page. This is messaging only; it does not restrict who can register.'),
        ),
    ]
