# Generated by Django 5.2.14 on 2026-07-30 20:28

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_event_open_to_guests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ce_credits',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if the body has not set a count yet.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='event',
            name='ce_credits_basis',
            field=models.CharField(choices=[('total', 'in total'), ('per_meeting', 'per meeting')], default='total', max_length=12),
        ),
        migrations.AddField(
            model_name='event',
            name='ce_note',
            field=models.TextField(blank=True, help_text='Anything specific to this event, e.g. full attendance required for credit.'),
        ),
        migrations.AddField(
            model_name='event',
            name='offers_ce',
            field=models.BooleanField(default=False, verbose_name='Approved for CE credits'),
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='ce_credits',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If you know it yet. You can set or change this later.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='ce_credits_basis',
            field=models.CharField(choices=[('total', 'in total'), ('per_meeting', 'per meeting')], default='total', max_length=12),
        ),
        migrations.CreateModel(
            name='CEOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo', models.ImageField(upload_to='ce-organizations/')),
                ('url', models.URLField(blank=True, help_text="The organization's site. Links the logo when set.")),
                ('statement', models.TextField(blank=True, help_text='Approval language this body requires on approved events. Shown under its logo on every event that claims it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ce_organizations_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='ce_organizations',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.ceorganization', verbose_name='Approved by'),
        ),
        migrations.AddConstraint(
            model_name='ceorganization',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='ce_organization_name_ci_unique'),
        ),
    ]
