# Generated by Django 5.2.14 on 2026-07-31 20:25
#
# Hand-edited (task #486): makemigrations emitted RemoveField *before*
# CreateModel. The operations are reordered so the new table exists and the old
# column is still readable when the data step runs between them.

import django.db.models.deletion
from django.db import migrations, models


def copy_logo_to_set(apps, schema_editor):
    """Move each organization's single logo onto a first CEOrganizationLogo row.

    Assigns the stored path rather than the file, so nothing is re-uploaded and
    the existing object keeps its key.
    """
    CEOrganization = apps.get_model("events", "CEOrganization")
    CEOrganizationLogo = apps.get_model("events", "CEOrganizationLogo")
    for org in CEOrganization.objects.exclude(logo="").exclude(logo=None):
        CEOrganizationLogo.objects.create(
            organization=org, image=org.logo.name, sort_order=1,
        )


def copy_set_to_logo(apps, schema_editor):
    """Reverse: put the first logo back on the organization."""
    CEOrganization = apps.get_model("events", "CEOrganization")
    CEOrganizationLogo = apps.get_model("events", "CEOrganizationLogo")
    for org in CEOrganization.objects.all():
        first = CEOrganizationLogo.objects.filter(
            organization=org,
        ).order_by("sort_order", "pk").first()
        if first is not None:
            org.logo = first.image.name
            org.save(update_fields=["logo"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_ce_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEOrganizationLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ce-organizations/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='events.ceorganization')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.RunPython(copy_logo_to_set, copy_set_to_logo),
        migrations.RemoveField(
            model_name='ceorganization',
            name='logo',
        ),
    ]
