# Generated by Django 5.2.14 on 2026-07-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_ce_organization_logos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceorganization',
            name='statement',
            field=models.TextField(blank=True, help_text='Approval language this body requires on approved events. Shown under its logos on every event that claims it.'),
        ),
        migrations.AlterField(
            model_name='ceorganization',
            name='url',
            field=models.URLField(blank=True, help_text="The organization's site. Links the logos when set."),
        ),
    ]
