# Generated by Django 5.2.14 on 2026-08-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_ce_logo_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventproposal',
            name='speaker_arrangement',
            field=models.CharField(blank=True, choices=[('proposer', "I'll arrange with the speaker(s) directly"), ('pc', "I'd like the Program Committee to arrange it")], default='proposer', help_text='Who contacts/arranges with the speakers.', max_length=12),
        ),
    ]
