# Generated by Django 5.2.14 on 2026-08-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_alter_eventproposal_speaker_arrangement'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingcode',
            name='installments',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = pay in full at registration. A higher number splits the fee into that many payments, the first due at registration and the rest monthly. The total never changes.'),
        ),
        migrations.AlterField(
            model_name='pricingcode',
            name='pricing_mode',
            field=models.CharField(choices=[('percent_off', 'Percent off'), ('fixed_amount', 'Fixed amount'), ('sliding_floor', 'Sliding-scale floor'), ('full_price', 'Full price — payment plan only')], max_length=20),
        ),
    ]
