# Generated by Django 5.2.14 on 2026-08-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_pricingcode_installments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingcode',
            name='installments',
            field=models.PositiveSmallIntegerField(default=1, help_text="1 = pay in full at registration. A higher number splits the fee into that many payments, the first due at registration and the rest spread across the event's run. The total never changes."),
        ),
    ]
