# Generated by Django 5.2.14 on 2026-08-05 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_pricingcode_installments_help'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='image_height', help_text='Rendered WebP, derived from the upload via feature_images.render().', upload_to='events/feature/%Y/', width_field='image_width')),
                ('image_width', models.PositiveIntegerField(default=0)),
                ('image_height', models.PositiveIntegerField(default=0)),
                ('original', models.ImageField(blank=True, help_text='The bounded upload, kept so the framing can be revised later.', upload_to='events/feature/originals/%Y/')),
                ('crop', models.JSONField(blank=True, help_text='Cropper.js rect in natural-image pixels, so the framing modal reopens where it was left.', null=True)),
                ('credit', models.CharField(blank=True, help_text='Shown small under the image, e.g. "René Magritte, The Treachery of Images".', max_length=200)),
                ('alt', models.CharField(blank=True, help_text='Description for screen readers. Blank falls back to the event title.', max_length=300)),
                ('source', models.CharField(choices=[('public_domain', 'Public domain'), ('licensed', 'Licensed'), ('own_work', 'My own work'), ('permission', 'Permission granted by the rights holder')], max_length=20)),
                ('source_url', models.URLField(blank=True, help_text='Required when the source is Licensed.')),
                ('rights_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_image', to='events.event')),
                ('rights_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
