# Generated by Django 5.2.14 on 2026-08-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_eventfeatureimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfeatureimage',
            name='image_full',
            field=models.ImageField(blank=True, height_field='image_full_height', help_text='Larger render for the full-size view. Blank when the upload was too small for this to differ from `image`.', upload_to='events/feature/full/%Y/', width_field='image_full_width'),
        ),
        migrations.AddField(
            model_name='eventfeatureimage',
            name='image_full_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventfeatureimage',
            name='image_full_width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
