# Generated by Django 5.2.14 on 2026-08-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_eventfeatureimage_image_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchangerequest',
            name='original_price',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventchangerequest',
            name='proposed_price',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
