# Generated by Django 5.2.14 on 2026-08-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_changerequest_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='requires_faculty_approval',
            field=models.BooleanField(default=False, help_text="If set, each new registration waits for the event's faculty (or a reading group's conveners) to approve it. Anyone already registered keeps their place; unsetting it approves everyone still waiting."),
        ),
    ]
