# Generated by Django 5.2.14 on 2026-08-12 22:25
#
# Task #566 — the messaging-only ``open_to_guests`` becomes an enforced
# eligibility choice. Add, copy, drop: the AddField default already writes
# ``members_and_guests`` everywhere, so forward only has to move the rows
# that had the flag unticked.

from django.db import migrations, models


def _copy_forward(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Event.objects.filter(open_to_guests=False).update(
        registration_eligibility="members_only"
    )
    # A members-only *visibility* also carries over, once. Until now the
    # guests-welcome note was suppressed for those events as well, so an
    # existing one saying "members only" in the only way the site could say
    # it should keep meaning that. Going forward the two axes are
    # independent — visibility is who can see the page, eligibility is who
    # can register — and this reconciliation does not repeat.
    Event.objects.filter(visibility="members_only").update(
        registration_eligibility="members_only"
    )


def _copy_back(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Event.objects.update(open_to_guests=True)
    Event.objects.filter(registration_eligibility="members_only").update(
        open_to_guests=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_changerequest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_eligibility',
            field=models.CharField(choices=[('members_and_guests', 'Members and guests'), ('members_only', 'Members only')], default='members_and_guests', help_text='Members only limits registration to members of the School. Members and guests lets anyone with a free account register, and shows a guests-welcome note on the event page.', max_length=20, verbose_name='Who can register'),
        ),
        migrations.RunPython(_copy_forward, _copy_back),
        migrations.RemoveField(
            model_name='event',
            name='open_to_guests',
        ),
    ]
