# Generated by Django 5.2.14 on 2026-08-21 05:14

from django.db import migrations, models


def carry_external_venue_across(apps, schema_editor):
    """Task #624. Before this field existed, the only way to say "we meet on
    Zoom" was to put the link in ``access_info`` and live with the site
    offering its own room beside it. Those events mean EXTERNAL.

    Scoped to ``format="online"`` on purpose: a hybrid event's ``access_info``
    holds its *venue address* (EventProposal.approve writes it there), and a
    hybrid event still wants the in-site room. Safe to run once over today's
    data where it can be inspected; unsafe as a live predicate, which is why
    the field exists at all.
    """
    Event = apps.get_model("events", "Event")
    Event.objects.filter(format="online").exclude(access_info="").update(
        online_venue="external"
    )


def unset_external_venue(apps, schema_editor):
    """Reverse: everything goes back to the default the column had."""
    Event = apps.get_model("events", "Event")
    Event.objects.update(online_venue="insite")


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_registration_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='online_venue',
            field=models.CharField(choices=[('insite', "In the site's video room"), ('external', 'External link (Zoom, etc.)')], default='insite', help_text="Where an online or hybrid event meets. The site's own room needs no link — registrants get a Join button. Choose the external link to meet on Zoom or another service and put the link in the access details below; the site then stops offering its own room.", max_length=20),
        ),
        migrations.AlterField(
            model_name='eventproposal',
            name='location',
            field=models.CharField(blank=True, help_text="Venue address (in person or hybrid), or the meeting link for an external online event. Optional — the link can be added to the event later. Leave blank when meeting in the site's own video room.", max_length=300),
        ),
        migrations.AlterField(
            model_name='eventproposal',
            name='location_kind',
            field=models.CharField(choices=[('online_insite', 'Online — in-site video room'), ('online_external', 'Online — external link (Zoom, etc.)'), ('in_person', 'In person'), ('hybrid', 'Hybrid (in person + online)')], default='online_insite', help_text='Where it meets.', max_length=20),
        ),
        migrations.RunPython(
            carry_external_venue_across, unset_external_venue, elidable=False
        ),
    ]
