# Generated by Django 5.2.14 on 2026-08-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_event_online_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='online_venue',
            field=models.CharField(choices=[('insite', "In the site's video room"), ('external', 'External link (Zoom, etc.)')], default='insite', help_text="Where an online or hybrid event meets. The site's own room is recommended for most meetings and needs no link — registrants get a Join button. Choose the external link to meet on Zoom or another service (recommended if you use breakout groups) and put the link in the access details below; the site then stops offering its own room.", max_length=20),
        ),
    ]
