# Generated by Django 5.2.14 on 2026-09-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_joining_instructions_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, editable=False, help_text="When the day-before reminder went to this session's registrants (task #716); null until sent.", null=True),
        ),
    ]
