# Generated by Django 5.2.14 on 2026-09-20 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_session_reminder_sent_at'),
        ('workgroups', '0025_meetingseries_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventproposal',
            name='continues_seminar',
            field=models.ForeignKey(blank=True, help_text='Optional: propose a new yearly term of this existing seminar or reading group.', limit_choices_to={'kind__in': ('seminar', 'reading_group')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminar_proposals', to='workgroups.workgroup'),
        ),
    ]
