# Generated by Django 5.2.14 on 2026-09-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_eventproposal_continue_reading_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventproposal',
            name='event_type',
            field=models.CharField(choices=[('seminar', 'Seminar'), ('reading_group', 'Reading group'), ('special_event', 'Special event'), ('day_of_assembly', 'Day of Assembly'), ('working_day', 'Working Day'), ('scholarly_seminar', 'Scholarly Seminar Series')], default='seminar', help_text="What kind of event you're proposing.", max_length=20),
        ),
    ]
