# Generated by Django 5.2.14 on 2026-05-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aphorism",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField(help_text="The visible aphorism.")),
                (
                    "short_attribution",
                    models.CharField(
                        blank=True,
                        help_text="Small chip shown next to the quote (e.g. “Seminar XI”).",
                        max_length=120,
                    ),
                ),
                (
                    "full_attribution",
                    models.TextField(
                        blank=True,
                        help_text="Bibliographic detail; shown as the hover tooltip.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active aphorisms appear in the footer rotation.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("short_attribution", "pk"),
            },
        ),
    ]
