# Generated by Django 5.2.14 on 2026-05-31 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_aphorisms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable identifier code uses to gate a control panel. Don't rename an existing key — it would orphan its panel.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                (
                    "holders",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who hold this role (superusers hold every role).",
                        related_name="staff_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
