# Generated by Django 5.2.14 on 2026-05-30 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("committees", "0004_alter_committeemembership_role_in_committee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "position",
                    models.IntegerField(
                        default=0,
                        help_text="Sort order in the sidebar. Lower = earlier.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "channel categories",
                "ordering": ("position", "name"),
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("forum", "Forum (threaded)"),
                            ("chat", "Chat (live stream)"),
                        ],
                        default="forum",
                        max_length=8,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="One- or two-line topic shown under the channel name.",
                    ),
                ),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("open", "Open — every member"),
                            ("role", "Specific roles"),
                            ("committee", "Committee"),
                            ("private", "Private — named members"),
                        ],
                        default="open",
                        help_text="Who may see and read this channel. Every channel — even Open — is members-only; Parlêtre is never visible to the public.",
                        max_length=16,
                    ),
                ),
                (
                    "allowed_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="When access=role: a list of Profile.role values (e.g. ['analyst', 'candidate']).",
                    ),
                ),
                (
                    "post_policy",
                    models.CharField(
                        choices=[
                            ("open", "Any member may post"),
                            ("staff_only", "Moderators / staff only"),
                        ],
                        default="open",
                        help_text="Use 'Moderators / staff only' for an announcements channel.",
                        max_length=16,
                    ),
                ),
                (
                    "auto_subscribe",
                    models.BooleanField(
                        default=False,
                        help_text="Force every member subscribed (downgradable to digest, not off). Use for the list-wide Announcements channel.",
                    ),
                ),
                (
                    "default_subscription_level",
                    models.CharField(
                        choices=[
                            ("all", "Every post"),
                            ("threads_only", "New threads only"),
                            ("mentions_only", "Mentions only"),
                            ("digest", "Digest only"),
                            ("muted", "Muted"),
                        ],
                        default="digest",
                        help_text="Subscription level applied when a member first joins, unless auto_subscribe overrides it.",
                        max_length=16,
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        default=0,
                        help_text="Sort order within the category. Lower = earlier.",
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(
                        default=False,
                        help_text="Hidden from members; lingers for moderators.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "committee",
                    models.ForeignKey(
                        blank=True,
                        help_text="When access=committee: members of this committee may enter; its chairs moderate.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parletre_channels",
                        to="committees.committee",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="When access=private: the explicit member list.",
                        related_name="parletre_private_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moderators",
                    models.ManyToManyField(
                        blank=True,
                        help_text="May pin / lock / move / delete in this channel.",
                        related_name="parletre_moderated_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="channels",
                        to="parletre.channelcategory",
                    ),
                ),
            ],
            options={
                "ordering": ("category__position", "position", "name"),
            },
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220)),
                ("pinned", models.BooleanField(default=False)),
                (
                    "locked",
                    models.BooleanField(
                        default=False,
                        help_text="No further replies; existing posts stay.",
                    ),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Bumped on each new post; drives thread ordering.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parletre_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="parletre.channel",
                    ),
                ),
            ],
            options={
                "ordering": ("-pinned", "-last_activity_at"),
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(help_text="Markdown.")),
                (
                    "via_email",
                    models.BooleanField(
                        default=False, help_text="Posted via reply-by-email (DISC-7)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft tombstone; body hidden but slot kept.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parletre_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="parletre.channel",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set to quote / inline-reply to another post.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="parletre.post",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="parletre.thread",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="parletre.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parletre_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("post", "user", "emoji"),
                        name="parletre_one_reaction_per_user_emoji",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("all", "Every post"),
                            ("threads_only", "New threads only"),
                            ("mentions_only", "Mentions only"),
                            ("digest", "Digest only"),
                            ("muted", "Muted"),
                        ],
                        default="digest",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="parletre.channel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parletre_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "channel"),
                        name="parletre_one_subscription_per_user_channel",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.UniqueConstraint(
                fields=("channel", "slug"),
                name="parletre_unique_thread_slug_per_channel",
            ),
        ),
    ]
