# Generated by Django 5.2.14 on 2026-05-30 18:18

import parletre.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parletre", "0004_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                storage=parletre.storage.attachment_storage, upload_to="%Y/%m/"
            ),
        ),
    ]
