# Generated by Django 5.2.14 on 2026-05-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parletre", "0007_inboundemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="message_ttl_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="If set, messages here disappear this many seconds after posting (a 'disappearing' chat, e.g. Purloined Letters). Null = permanent.",
                null=True,
            ),
        ),
    ]
