# Generated by Django 5.2.14 on 2026-05-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parletre", "0008_channel_message_ttl_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="redacted",
            field=models.BooleanField(
                default=False,
                help_text="A disappearing-channel message whose content has been redacted (real text/files deleted; a blacked-out bar remains).",
            ),
        ),
    ]
