# Generated by Django 5.2.14 on 2026-05-31 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parletre", "0009_post_redacted"),
        ("workgroups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="workgroup",
            field=models.ForeignKey(
                blank=True,
                help_text="When access=workgroup: members of this workgroup may enter; its chairs / plus-one moderate.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="workgroups.workgroup",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="access",
            field=models.CharField(
                choices=[
                    ("open", "Open — every member"),
                    ("role", "Specific roles"),
                    ("committee", "Committee"),
                    ("workgroup", "Workgroup"),
                    ("private", "Private — named members"),
                ],
                default="open",
                help_text="Who may see and read this channel. Every channel — even Open — is members-only; Parlêtre is never visible to the public.",
                max_length=16,
            ),
        ),
    ]
