# Generated by Django 5.2.14 on 2026-05-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parletre", "0010_channel_workgroup_alter_channel_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="access",
            field=models.CharField(
                choices=[
                    ("open", "Open — every member"),
                    ("role", "Specific roles"),
                    ("committee", "Committee"),
                    ("workgroup", "Workgroup"),
                    ("lsp_staff", "LSP Staff"),
                    ("private", "Private — named members"),
                ],
                default="open",
                help_text="Who may see and read this channel. Every channel — even Open — is members-only; Parlêtre is never visible to the public.",
                max_length=16,
            ),
        ),
    ]
