# Generated by Django 5.2.14 on 2026-06-01 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parletre", "0012_backfill_workgroup_chat_channels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The member who created this chat (member-made private chats only); they may manage participants and delete it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parletre_created_channels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
