# Generated by Django 5.2.14 on 2026-06-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parletre", "0013_channel_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="kind",
            field=models.CharField(
                choices=[
                    ("forum", "Forum (threaded)"),
                    ("chat", "Chat (live stream)"),
                    ("video", "Video (meeting room)"),
                ],
                default="forum",
                max_length=8,
            ),
        ),
    ]
