# Generated by Django 5.2.14 on 2026-06-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parletre", "0016_alter_channel_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="recording_mode",
            field=models.CharField(
                choices=[
                    ("on_demand", "On demand — hosts can record"),
                    ("off", "Off — no Record button"),
                ],
                default="on_demand",
                help_text="For video channels: whether hosts see a Record button. Set to Off for open rooms like The Gaze.",
                max_length=12,
            ),
        ),
    ]
