# Generated by Django 5.2.14 on 2026-06-07 20:38

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("bug", "Something's broken"),
                            ("content", "Wording / typo / content"),
                            ("feature", "New feature or idea"),
                            ("design", "Design / layout"),
                            ("other", "Something else"),
                        ],
                        default="other",
                        help_text="What kind of change you're suggesting.",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="What you'd change, and (for a bug) what you expected instead.",
                    ),
                ),
                ("page_url", models.CharField(blank=True, max_length=500)),
                ("page_title", models.CharField(blank=True, max_length=300)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        help_text="Optional screenshot (private — submitter and staff only).",
                        null=True,
                        storage=core.storage.private_storage,
                        upload_to="suggestions/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("acknowledged", "Acknowledged"),
                            ("planned", "Planned"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("declined", "Declined"),
                        ],
                        default="new",
                        max_length=12,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "staff_notes",
                    models.TextField(
                        blank=True,
                        help_text="Triage notes (staff-only; not shown to the submitter).",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("exported_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
