# Generated by Django 5.2.14 on 2026-06-12 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('acknowledgment', 'Acknowledgment (process reply)'), ('distribution', 'Distribution to the referral list'), ('followup_many', 'Follow-up — several clinicians'), ('followup_one', 'Follow-up — a single clinician'), ('followup_none', 'Follow-up — no responses'), ('onboarding', 'New Member Instructions')], max_length=30, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='ReferralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('pronouns', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=80)),
                ('modalities', models.CharField(blank=True, max_length=200)),
                ('additional_information', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('distributed', 'Distributed — collecting responses'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('responses_due_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('coordinator_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ack_mode', models.CharField(choices=[('auto', 'Automatic'), ('review', 'Review first')], default='auto', help_text='The process reply to the requester after they submit.', max_length=10, verbose_name='Acknowledgment (step 2)')),
                ('distribution_mode', models.CharField(choices=[('auto', 'Automatic'), ('review', 'Review first')], default='review', help_text='Sending the anonymized request to the referral list. Automatic sends it as soon as the request arrives; review first waits for you to press Distribute on the request page.', max_length=10, verbose_name='Distribution (step 3)')),
                ('followup_mode', models.CharField(choices=[('auto', 'Automatic'), ('review', 'Review first')], default='review', help_text='The reply to the requester with available clinicians. Automatic sends the assembled draft when the response window closes; review first leaves it for you to adjust and send.', max_length=10, verbose_name='Follow-up (step 5)')),
                ('onboarding_mode', models.CharField(choices=[('auto', 'Automatic'), ('review', 'Review first')], default='auto', help_text='The New Member Instructions sent when a clinician is added to the referral list.', max_length=10, verbose_name='New-member onboarding')),
                ('response_window_days', models.PositiveSmallIntegerField(default=10, help_text='How long clinicians have to respond after distribution.')),
                ('retention_months', models.PositiveSmallIntegerField(default=12, help_text='Months after a request is replied/closed before its identifying details are redacted.')),
            ],
            options={
                'verbose_name': 'Referral settings',
                'verbose_name_plural': 'Referral settings',
            },
        ),
        migrations.CreateModel(
            name='ReferralListMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive members stay on record but receive no requests.')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('onboarded_at', models.DateTimeField(blank=True, help_text='When the New Member Instructions were sent.', null=True)),
                ('details_override', models.TextField(blank=True, help_text="If set, sent to requesters verbatim instead of the block built from the member's profile.")),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_listing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__last_name', 'user__first_name'),
            },
        ),
        migrations.CreateModel(
            name='ReferralResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, help_text='Optional note to the coordinator.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='referrals.referrallistmember')),
                ('recorded_by', models.ForeignKey(blank=True, help_text="Set when the coordinator recorded this on the clinician's behalf.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='referrals.referralrequest')),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('request', 'member'), name='unique_response_per_member')],
            },
        ),
    ]
