# Generated by Django 5.2.14 on 2026-07-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_seed_message_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('honeypot', 'Honeypot field filled'), ('timing', 'Submitted too fast'), ('rate_limit', 'Rate limit')], max_length=20)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='held_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='held_escalated_at',
            field=models.DateTimeField(blank=True, help_text='When the unreviewed-hold reminder was emailed, so it is sent only once.', null=True),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='held_reason',
            field=models.TextField(blank=True, help_text='Why screening held this submission, shown to the coordinator so they can judge it at a glance.'),
        ),
        migrations.AddField(
            model_name='referralsettings',
            name='held_escalation_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Days a held submission may sit unreviewed before the coordinator is emailed about it. Held requests otherwise only ring the notification bell.'),
        ),
        migrations.AlterField(
            model_name='referralrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('distributed', 'Distributed — collecting responses'), ('replied', 'Replied'), ('closed', 'Closed'), ('held', 'Held for review'), ('junk', 'Junk')], default='new', max_length=20),
        ),
    ]
