# Generated by Django 5.2.14 on 2026-08-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_blockedsubmission_referralrequest_held_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralrequest',
            name='distributed_to',
            field=models.ManyToManyField(blank=True, help_text='Clinicians who have received this request, whether by the original distribution or a later addendum.', related_name='distributed_requests', to='referrals.referrallistmember'),
        ),
    ]
