# Generated by Django 5.2.14 on 2026-08-09 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_referralrequest_distributed_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='key',
            field=models.CharField(choices=[('acknowledgment', 'Acknowledgment (process reply)'), ('distribution', 'Distribution to the referral list'), ('followup_many', 'Follow-up — several clinicians'), ('followup_one', 'Follow-up — a single clinician'), ('followup_none', 'Follow-up — no responses'), ('onboarding', 'New Member Instructions'), ('addendum', 'Addendum to a distributed request')], max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='ReferralAddendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audience', models.CharField(choices=[('distributed', 'Clinicians this request went to'), ('all', 'Everyone on the referral list')], default='distributed', max_length=20)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addenda', to='referrals.referralrequest')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'referral addenda',
                'ordering': ('sent_at',),
            },
        ),
    ]
