# Generated by Django 5.2.14 on 2026-09-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0005_alter_messagetemplate_key_referraladdendum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralsettings',
            name='response_window_days',
            field=models.PositiveSmallIntegerField(default=10, help_text='How long clinicians have to respond, counted from the day the request was received (not the day it was distributed). You can change the date on each request before sending.'),
        ),
    ]
