# Generated by Django 5.2.14 on 2026-06-03 03:00

import admissions.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "track",
                    models.CharField(
                        choices=[
                            ("analyst", "Analyst formation"),
                            ("scholar", "Scholar formation"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "background",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("academic", "Academic background"),
                            ("clinical", "Clinical background"),
                        ],
                        help_text="Analyst track: academic or clinical background.",
                        max_length=10,
                    ),
                ),
                (
                    "eligibility_note",
                    models.CharField(
                        blank=True,
                        help_text="Degree / licensure (analyst) or where the year of personal analysis took place (scholar).",
                        max_length=255,
                    ),
                ),
                (
                    "letter_of_intent",
                    models.TextField(
                        help_text="Interest and goals in the study of Freudian and Lacanian psychoanalysis and the chosen formation."
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        blank=True,
                        storage=admissions.storage.cv_storage,
                        upload_to="cv/%Y/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted — awaiting review"),
                            ("interviewing", "In interviews"),
                            ("accepted", "Accepted"),
                            ("rejected", "Not accepted"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=14,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                (
                    "staff_notes",
                    models.TextField(blank=True, help_text="Internal reviewer notes."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-submitted_at",),
            },
        ),
        migrations.CreateModel(
            name="ApplicationInterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_at",
                    models.DateField(
                        blank=True,
                        help_text="Date the interview took place; blank = pending.",
                        null=True,
                    ),
                ),
                (
                    "report",
                    models.TextField(
                        blank=True,
                        help_text="The interviewer's report / recommendation.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="admissions.application",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "interviewer"),
                        name="admissions_one_interview_per_interviewer",
                    )
                ],
            },
        ),
    ]
