# Generated by Django 5.2.14 on 2026-06-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_messagetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledgment_mode', models.CharField(choices=[('auto', 'Automatic'), ('review', 'Review first')], default='auto', help_text='Automatic emails the acknowledgment as soon as an application is submitted; review first holds it for you to send (and personalize) from the console.', max_length=10, verbose_name='Applicant acknowledgment')),
            ],
            options={
                'verbose_name': 'Admissions settings',
                'verbose_name_plural': 'Admissions settings',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When the applicant acknowledgment was sent (auto on submit, or by the coordinator in review-first mode).', null=True),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='key',
            field=models.CharField(choices=[('acknowledgment', 'Applicant acknowledgment (on submit)'), ('interviewer_nudge', 'Interviewer report reminder'), ('decision_accept', 'Decision — accepted'), ('decision_reject', 'Decision — not accepted')], max_length=40, unique=True),
        ),
    ]
