# Generated by Django 5.2.14 on 2026-06-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_admissionssettings_application_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionssettings',
            name='invitation_mode',
            field=models.CharField(choices=[('auto', 'Automatic'), ('review', 'Review first')], default='review', help_text='Automatic emails available analysts to invite them to interview as soon as an application arrives; review first waits for you to press Invite on the application.', max_length=10, verbose_name='Call for interviewers'),
        ),
        migrations.AddField(
            model_name='application',
            name='interviewers_invited_at',
            field=models.DateTimeField(blank=True, help_text='When the call for interviewers went out to available analysts.', null=True),
        ),
        migrations.AddField(
            model_name='applicationinterview',
            name='agreed_at',
            field=models.DateTimeField(blank=True, help_text='When the analyst agreed to interview (or was assigned).', null=True),
        ),
        migrations.AddField(
            model_name='applicationinterview',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, help_text='Last weekly reminder to set up / report the interview.', null=True),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='key',
            field=models.CharField(choices=[('acknowledgment', 'Applicant acknowledgment (on submit)'), ('invitation', 'Call for interviewers (to analysts)'), ('introduction', 'Introduction (applicant ↔ interviewer)'), ('interview_reminder', 'Interview reminder (to interviewer)'), ('decision_accept', 'Decision — accepted'), ('decision_reject', 'Decision — not accepted')], max_length=40, unique=True),
        ),
    ]
