# Generated by Django 5.2.14 on 2026-05-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Short biographical text. Shown on event pages for faculty.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="default_billing_mode",
            field=models.CharField(
                blank=True,
                choices=[("per_class", "Per class"), ("per_seminar", "Per seminar")],
                help_text="Faculty default for new seminars (REG-6). Null for non-faculty.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="headshot",
            field=models.ImageField(blank=True, null=True, upload_to="headshots/%Y/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_faculty",
            field=models.BooleanField(
                default=False, help_text="Faculty axis (USR-6). Orthogonal to role."
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="public",
            field=models.BooleanField(
                default=False,
                help_text="Whether to show bio/headshot on public-facing pages.",
            ),
        ),
    ]
