# Generated by Django 5.2.14 on 2026-05-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_bio_profile_default_billing_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("prospective_applicant", "Prospective applicant"),
                    ("student", "Student"),
                    ("pre_candidate", "Pre-candidate"),
                    ("candidate", "Candidate"),
                    ("analyst", "Analyst"),
                    ("member", "Member"),
                    ("external", "Guest"),
                ],
                default="external",
                help_text="LSP standing; drives event pricing and members-only access.",
                max_length=32,
            ),
        ),
    ]
