# Generated by Django 5.2.14 on 2026-05-28 06:47

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="credentials",
            field=models.CharField(
                blank=True,
                help_text="Degrees, licenses, board cert (e.g. 'PhD; CA Licensed Psychologist PSY 22767').",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="languages_spoken",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated languages (e.g. 'English, French, Spanish').",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Free-form city/region/country (e.g. 'Los Gatos, CA, USA').",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Stored in E.164 form. Parsed assuming US if no country code.",
                max_length=128,
                region=None,
            ),
        ),
    ]
