# Generated by Django 5.2.14 on 2026-05-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_credentials_profile_languages_spoken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="public_email",
            field=models.EmailField(
                blank=True,
                help_text="Public-facing email for directories / event pages. Distinct from the login email (User.email) since members often use one address for their professional listing and another for school correspondence. Falls back to User.email when unset (see Profile.display_email).",
                max_length=254,
            ),
        ),
    ]
