# Generated by Django 5.2.14 on 2026-05-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_public_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("prospective_applicant", "Prospective Applicant"),
                    ("student", "Student"),
                    ("pre_candidate", "Pre-Candidate Analyst"),
                    ("candidate", "Candidate Analyst"),
                    ("analyst", "Analyst"),
                    ("pre_candidate_scholar", "Pre-Candidate Scholar"),
                    ("candidate_scholar", "Candidate Scholar"),
                    ("scholar", "Scholar"),
                    ("member", "Member"),
                    ("external", "Guest"),
                ],
                default="external",
                help_text="LSP standing; drives event pricing and members-only access.",
                max_length=32,
            ),
        ),
    ]
