# Generated by Django 5.2.14 on 2026-05-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="event_bio",
            field=models.TextField(
                blank=True,
                help_text="Optional alternate bio used when this member is shown as a speaker on an event page. Falls back to ``bio`` when blank.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Short biographical text. Shown on the directory and on event pages.",
            ),
        ),
    ]
