# Generated by Django 5.2.14 on 2026-05-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_profile_event_bio_alter_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="accepting_patients",
            field=models.BooleanField(
                default=True,
                help_text="Whether this member is currently accepting new patients/analysands. Drives a pin filter on the Find-an-Analyst map.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="location_lat",
            field=models.FloatField(
                blank=True,
                help_text="Latitude geocoded from ``location`` for the Find-an-Analyst map (M11).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="location_lng",
            field=models.FloatField(
                blank=True, help_text="Longitude geocoded from ``location``.", null=True
            ),
        ),
    ]
