# Generated by Django 5.2.14 on 2026-05-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_profile_accepting_patients_profile_location_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location_pins",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {lat, lng, label} dicts for the Find-an-Analyst map. Populated by geocode_profiles by splitting ``location`` on ' & ', ' and ', or '/'. Empty list ⇒ render just (location_lat, location_lng) as a single pin.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location_lat",
            field=models.FloatField(
                blank=True,
                help_text="Latitude of the *primary* geocoded location. For members with a single location this is the only coord; for members listing two (e.g. 'San Francisco & Palo Alto, CA') see ``location_pins`` for the full set.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location_lng",
            field=models.FloatField(
                blank=True,
                help_text="Longitude of the primary geocoded location.",
                null=True,
            ),
        ),
    ]
