# Generated by Django 5.2.14 on 2026-05-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_profile_location_pins_alter_profile_location_lat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="tuition_paying",
        ),
    ]
