# Generated by Django 5.2.14 on 2026-05-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_profile_tuition_paying"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="User's preferred timezone (IANA name, e.g. 'America/New_York'). Empty = use project default (Pacific Time).",
                max_length=64,
            ),
        ),
    ]
