# Generated by Django 5.2.14 on 2026-05-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_profile_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="consultation_modalities",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated subset of Modality values (in_person, phone, video) describing how this member meets analysands. Drives the Find-an-Analyst modality filter.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Preferred name to show instead of first+last (e.g. a member who goes by a name other than their legal first name). Falls back to the User's first+last when blank (see Profile.display_full_name).",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="headshot_crop",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Cropper state {x, y, width, height, rotate, scaleX, scaleY} in natural-image pixels, so the cropper reopens where the member left it. Empty dict ⇒ no crop recorded yet.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="headshot_original",
            field=models.ImageField(
                blank=True,
                help_text="The full, uncropped upload. Retained so a member can reopen the cropper and re-center / re-zoom without re-uploading.",
                null=True,
                upload_to="headshots/originals/%Y/",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="pronouns",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'she/her', 'he/him', 'they/them'. Shown on the directory.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="specialties",
            field=models.TextField(
                blank=True,
                help_text="Areas of interest / clinical specialties / theoretical focus. Shown on the directory; feeds Find-an-Analyst context.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Personal or professional website, linked from the directory.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="year_joined",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Start year of the academic year this member joined the school (e.g. 2018 ⇒ 'AY 2018–2019'). Self-reported; we're harvesting it.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="headshot",
            field=models.ImageField(
                blank=True,
                help_text="The rendered square shown across the site (circle- and square-framed). Derived from ``headshot_original`` via the self-service cropper — set it through the cropper, not by hand.",
                null=True,
                upload_to="headshots/%Y/",
            ),
        ),
    ]
