# Generated by Django 5.2.14 on 2026-05-30 16:08

from django.db import migrations, models


def list_existing_members(apps, schema_editor):
    """`public` now gates the directory and defaults to listed. Existing rows
    were created under the old default (False), so flip them to True to keep
    everyone in the directory — members can opt out from the profile editor."""
    Profile = apps.get_model("accounts", "Profile")
    Profile.objects.filter(public=False).update(public=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_emailchangerequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="public",
            field=models.BooleanField(
                default=True,
                help_text="Whether this member is listed in the public member directory and the Find-an-Analyst map. Defaults to listed (the school lists members by default); members may opt out for privacy. Does not affect event pages they teach.",
            ),
        ),
        migrations.RunPython(list_existing_members, migrations.RunPython.noop),
    ]
