# Generated by Django 5.2.14 on 2026-05-30 16:22

import accounts.models
import phonenumber_field.modelfields
from django.db import migrations, models


def carry_phone_to_public(apps, schema_editor):
    """Existing ``phone`` values were imported from the public Wix directory
    and currently show publicly. Copy them into the new ``public_phone`` so
    those members keep their listed number (field_visibility defaults 'phone'
    to Public). Members can clear public_phone to unlist it."""
    Profile = apps.get_model("accounts", "Profile")
    for p in Profile.objects.exclude(phone="").filter(public_phone=""):
        p.public_phone = p.phone
        p.save(update_fields=["public_phone"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_profile_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="field_visibility",
            field=models.JSONField(
                blank=True,
                default=accounts.models.default_field_visibility,
                help_text="Per-field visibility map {field_key: 'public'|'members'|'private'} for TOGGLEABLE_PUBLIC_FIELDS. 'members' shows only to authenticated users; 'private' only to staff (and the member). Applied wherever the field is rendered — see Profile.visible_to().",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="public_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Public-facing phone shown on the directory. Distinct from ``phone`` (kept on file for staff and never shown publicly) so a member can list an office line while keeping a personal number private. Unlike email, this does NOT fall back to ``phone``.",
                max_length=128,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Private/on-file number for staff; never shown publicly. The publicly listed number is ``public_phone``. E.164; parsed as US if no country code.",
                max_length=128,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="public",
            field=models.BooleanField(
                default=True,
                help_text="Master switch: whether this member is listed in the public member directory and the Find-an-Analyst map at all. Defaults to listed (the school lists members by default); members may opt out for privacy. Does not affect event pages they teach.",
            ),
        ),
        migrations.RunPython(carry_phone_to_public, migrations.RunPython.noop),
    ]
