# Generated by Django 5.2.14 on 2026-05-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_phone_visibility_members_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_lsp_staff",
            field=models.BooleanField(
                default=False,
                help_text="LSP Staff designation — distinct from Django's is_staff. Grants the Staff Parlêtre channel, board entry, and event-edit rights (replaces the former 'LSP Staff' committee). Orthogonal to role.",
            ),
        ),
    ]
