# Generated by Django 5.2.14 on 2026-05-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_profile_is_lsp_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_cartel_coordinator",
            field=models.BooleanField(
                default=False,
                help_text="Cartel Coordinator designation — reviews/approves cartel proposals (CART-4). Orthogonal to role.",
            ),
        ),
    ]
