# Generated by Django 5.2.14 on 2026-05-31 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_migrate_staff_flags_to_roles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_cartel_coordinator",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_lsp_staff",
        ),
    ]
