# Generated by Django 5.2.14 on 2026-06-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_persona",
            field=models.BooleanField(
                default=False,
                help_text="A disposable test persona (not a real member). The Web Coordinator may impersonate personas with full write access; impersonating a real member is read-only. Seeded by `manage.py seed_personas`.",
            ),
        ),
    ]
