# Generated by Django 5.2.14 on 2026-06-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_profile_is_persona"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="calendar_token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
