# Generated by Django 5.2.14 on 2026-06-02 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_profile_is_persona"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberIntakeSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "year_joined",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "payment_names",
                    models.CharField(
                        blank=True,
                        help_text="Alternate name(s) the member used on payments.",
                        max_length=255,
                    ),
                ),
                (
                    "payment_emails",
                    models.CharField(
                        blank=True,
                        help_text="Other email(s) used for Stripe / PayPal.",
                        max_length=255,
                    ),
                ),
                ("grid", models.JSONField(blank=True, default=dict)),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the answers were reconciled into structured records.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_survey",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MembershipTenure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("prospective_applicant", "Prospective Applicant"),
                            ("student", "Student"),
                            ("pre_candidate", "Pre-Candidate Analyst"),
                            ("candidate", "Candidate Analyst"),
                            ("analyst", "Analyst"),
                            ("pre_candidate_scholar", "Pre-Candidate Scholar"),
                            ("candidate_scholar", "Candidate Scholar"),
                            ("scholar", "Scholar"),
                            ("member", "Member"),
                            ("external", "Auditor"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "start_ay",
                    models.PositiveSmallIntegerField(
                        help_text="Academic-year start year, e.g. 2019 for AY 2019–2020."
                    ),
                ),
                (
                    "end_ay",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="AY start year this role ended (inclusive); blank = ongoing.",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("verified", "Verified against records"),
                            ("imported", "Imported from treasurer ledger"),
                            ("self_reported", "Member-reported (survey)"),
                            ("assumed", "Assumed"),
                            ("staff", "Entered by staff"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("user", "start_ay"),
                "indexes": [
                    models.Index(
                        fields=["user", "start_ay"],
                        name="accounts_me_user_id_9d156a_idx",
                    )
                ],
            },
        ),
    ]
