# Generated by Django 5.2.14 on 2026-06-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_profile_calendar_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiptenure",
            name="standing",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("on_leave", "On leave"),
                    ("resigned", "Resigned"),
                    ("emeritus", "Emeritus"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="standing",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("on_leave", "On leave"),
                    ("resigned", "Resigned"),
                    ("emeritus", "Emeritus"),
                ],
                default="active",
                help_text="Membership standing (active / on leave / resigned / emeritus). Live cache; the Board sets it via Membership administration.",
                max_length=16,
            ),
        ),
    ]
