# Generated by Django 5.2.14 on 2026-06-03 03:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_membershiptenure_standing_profile_standing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advisorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Null = current advisor.", null=True
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advisee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisorships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advisees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("advisee", "-start_date"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("end_date__isnull", True)),
                        fields=("advisee",),
                        name="accounts_one_current_advisor_per_advisee",
                    )
                ],
            },
        ),
    ]
