# Generated by Django 5.2.14 on 2026-06-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_magicloginlink_totpdevice_recoverycode"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberintakesurvey",
            name="milestones",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Formation-step years, e.g. {"palimpsest": 2019, "passage": 2023}.',
            ),
        ),
    ]
