# Generated by Django 5.2.14 on 2026-06-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_memberintakesurvey_milestones"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberintakesurvey",
            name="paid_all_tuition",
            field=models.BooleanField(
                blank=True,
                help_text="Member's belief that they've paid all four years of full tuition to date (a fallback when records are incomplete).",
                null=True,
            ),
        ),
    ]
