# Generated by Django 5.2.14 on 2026-06-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_fix_psychoanalyst_bio_typo'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicloginlink',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magicloginlink',
            name='multi_use',
            field=models.BooleanField(default=False),
        ),
    ]
