# Generated by Django 5.2.14 on 2026-06-25 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_magicloginlink_expires_at_magicloginlink_multi_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='persona_owner',
            field=models.ForeignKey(blank=True, help_text='For a training-sandbox persona: the trainee who owns it. Mail addressed to this persona is redirected to the owner (tagged [SANDBOX]) instead of dropped, so they see the whole workflow. Set by `manage.py seed_sandbox`.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_personas', to=settings.AUTH_USER_MODEL),
        ),
    ]
