# Generated by Django 5.2.14 on 2026-07-12 00:42

from django.db import migrations, models


def backfill_clinical(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    Profile.objects.filter(role="analyst").update(clinical_background=True)


def unbackfill(apps, schema_editor):
    pass  # field is dropped on reverse; no-op


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_profile_persona_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clinical_background',
            field=models.BooleanField(default=False, help_text='Clinical background requires two control analyses (one of at least 4 years, one of at least 2 years); academic requires three (one of at least 4 years, two of at least 2 years). Set at acceptance from the application; adjustable by an advisor or admin.'),
        ),
        migrations.RunPython(backfill_clinical, unbackfill),
    ]
