# Generated by Django 5.2.14 on 2026-07-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_profile_clinical_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptenure',
            name='source',
            field=models.CharField(choices=[('verified', 'Verified against records'), ('imported', 'Imported from treasurer ledger'), ('stripe', 'Imported from Stripe'), ('self_reported', 'Member-reported (survey)'), ('assumed', 'Assumed'), ('staff', 'Entered by staff')], default='staff', max_length=20),
        ),
    ]
