# Generated by Django 5.2.14 on 2026-07-22 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_membershiptenure_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
