# Generated by Django 5.2.14 on 2026-07-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_welcomeemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deceased_on',
            field=models.DateField(blank=True, help_text="Date recorded as deceased. Orthogonal to standing — a member may be Retired and Deceased. Setting this disables the account (login off) for security; the member stays listed in the directory with an 'In memoriam' marker.", null=True),
        ),
        migrations.AlterField(
            model_name='membershiptenure',
            name='standing',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On leave'), ('resigned', 'Resigned'), ('emeritus', 'Emeritus'), ('retired', 'Retired'), ('removed', 'Removed')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='standing',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On leave'), ('resigned', 'Resigned'), ('emeritus', 'Emeritus'), ('retired', 'Retired'), ('removed', 'Removed')], default='active', help_text='Membership standing (active / on leave / resigned / emeritus / retired / removed). Live cache; the Board sets it via Membership administration.', max_length=16),
        ),
    ]
