# Generated by Django 5.2.14 on 2026-07-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_profile_deceased_on_alter_membershiptenure_standing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seminar_access_suspended',
            field=models.BooleanField(default=False, help_text='Treasurer-set: excluded from seminar group rosters until the outstanding balance is settled.'),
        ),
    ]
