# Generated by Django 5.2.14 on 2026-07-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_advisornote'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlanalysis',
            name='requirement',
            field=models.CharField(choices=[('four_year', '4-year'), ('two_year', '2-year')], default='four_year', help_text='Which requirement this analysis is meant to satisfy. Freely changeable between 4-year and 2-year.', max_length=10),
        ),
    ]
