# Generated by Django 5.2.14 on 2026-07-12 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_file'),
        ('formation', '0004_advisornote'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationsettings',
            name='analyst_formation_doc',
            field=models.ForeignKey(blank=True, help_text='Formation guidelines linked at the top of the Formation tab for analyst-track members in training.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document'),
        ),
        migrations.AddField(
            model_name='formationsettings',
            name='scholar_formation_doc',
            field=models.ForeignKey(blank=True, help_text='Formation guidelines linked at the top of the Formation tab for scholar-track members in training.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document'),
        ),
    ]
