# Generated by Django 5.2.14 on 2026-07-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_controlanalysis_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formationsettings',
            name='control_years_target',
        ),
        migrations.AddField(
            model_name='formationsettings',
            name='four_year_threshold',
            field=models.PositiveSmallIntegerField(default=4, help_text='Years for the longer (4-year) control analysis.'),
        ),
        migrations.AddField(
            model_name='formationsettings',
            name='two_year_threshold',
            field=models.PositiveSmallIntegerField(default=2, help_text='Years for each shorter (2-year) control analysis.'),
        ),
    ]
