# Generated by Django 5.2.14 on 2026-07-12 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0007_externalcontrolanalyst'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlanalysis',
            name='external_analyst',
            field=models.ForeignKey(blank=True, help_text='An approved external control analyst.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_analyses', to='formation.externalcontrolanalyst'),
        ),
        migrations.AddField(
            model_name='controlanalysis',
            name='school_analyst',
            field=models.ForeignKey(blank=True, help_text='An Analyst of the School, chosen from the directory.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_analyses_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controlanalysis',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
