# Generated by Django 5.2.14 on 2026-07-12 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_seed_formation_doc_links'),
        ('formation', '0008_controlanalysis_external_analyst_and_more'),
    ]

    operations = [
    ]
