# Generated by Django 5.2.14 on 2026-05-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "0003_rename_programming_committee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeemembership",
            name="role_in_committee",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("chair", "Chair"),
                    ("co_chair", "Co-chair"),
                    ("secretary", "Secretary"),
                    ("treasurer", "Treasurer"),
                    ("referral_coordinator", "Referral Coordinator"),
                    ("web_coordinator", "Web Coordinator"),
                    ("admin_assistant", "Admin Assistant"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
