# Generated by Django 5.2.14 on 2026-05-30 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("governance", "Governance"),
                            ("formation", "Formation Guidelines"),
                            ("founding", "Founding Texts"),
                            ("cartel_resource", "Cartel Resources"),
                            ("reference", "Reference"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="One-line description shown on the index card.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional longer-form description (markdown) for the detail page.",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/%Y/")),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("members", "Members only")],
                        default="public",
                        max_length=16,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True,
                        help_text="When this document took effect (for versioned docs like bylaws).",
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Sort key within the category. Lower = earlier.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when this document is replaced by a newer version.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ("category", "display_order", "title"),
            },
        ),
    ]
