# Generated by Django 5.2.14 on 2026-05-30 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_pdf_visibility(apps, schema_editor):
    """Copy listing_visibility into pdf_visibility for non-PUBLIC rows.

    Public listings stay PUBLIC for both axes (the AddField default).
    A document whose listing was members-only should also have a
    members-only PDF by default — operators can liberalize later.
    """
    Document = apps.get_model("documents", "Document")
    Document.objects.filter(listing_visibility="members").update(
        pdf_visibility="members"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rename preserves data — keeps any MEMBERS settings around.
        migrations.RenameField(
            model_name="document",
            old_name="visibility",
            new_name="listing_visibility",
        ),
        migrations.AlterField(
            model_name="document",
            name="listing_visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("members", "Members only")],
                default="public",
                help_text="Who can see this document exists in the index.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="notice",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Optional banner shown on the detail page and as a chip on the "
                    "index card — e.g. 'Under revision — procedural details may "
                    "change'. Leave blank when the document is settled."
                ),
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="pdf_visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("members", "Members only")],
                default="public",
                help_text=(
                    "Who can download the PDF. Cannot be more public than the "
                    "listing — e.g. listing=Members blocks a Public PDF."
                ),
                max_length=16,
            ),
        ),
        migrations.RunPython(
            backfill_pdf_visibility,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="DocumentAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorships",
                        to="documents.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_authorships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("display_order",),
            },
        ),
        migrations.AddField(
            model_name="document",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="authored_documents",
                through="documents.DocumentAuthor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="documentauthor",
            constraint=models.UniqueConstraint(
                fields=("document", "user"),
                name="documents_unique_author_per_document",
            ),
        ),
    ]
