# Generated by Django 5.2.14 on 2026-05-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_remove_document_visibility_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("governance", "Governance"),
                    ("formation", "Formation Guidelines"),
                    ("founding", "Founding Texts"),
                    ("cartel_resource", "Cartel Resources"),
                    ("newsletter", "Newsletters"),
                    ("reference", "Reference"),
                ],
                max_length=32,
            ),
        ),
    ]
