# Generated by Django 5.2.14 on 2026-05-31 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_document_category"),
        ("workgroups", "0002_alter_workgroup_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="owning_workgroup",
            field=models.ForeignKey(
                blank=True,
                help_text="The committee or working group that produced / owns this document. Both attach a Workgroup, so this one relation covers either — e.g. the Program Committee owns its proposal style guide.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="workgroups.workgroup",
            ),
        ),
    ]
