# Generated by Django 5.2.14 on 2026-06-03 03:04

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_rename_pdf_visibility_content_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                storage=core.storage.private_storage, upload_to="documents/%Y/"
            ),
        ),
    ]
