# Generated by Django 5.2.14 on 2026-07-13 01:36

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='body',
            field=models.TextField(blank=True, help_text='Inline document content (markdown), rendered on the detail page in place of a PDF. Supports the {{ annual_tuition }} placeholder, replaced with the current annual tuition figure. Use this for documents we hold as text rather than a PDF.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='The source PDF. Optional — leave blank for documents whose content is authored inline as HTML (the body field below).', storage=core.storage.private_storage, upload_to='documents/%Y/'),
        ),
    ]
