# Generated by Django 5.2.14 on 2026-08-15 23:43

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_tuition_assistance_is_the_payment_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('notice', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, storage=core.storage.private_storage, upload_to='documents/%Y/')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('listing_visibility', models.CharField(blank=True, max_length=16)),
                ('content_visibility', models.CharField(blank=True, max_length=16)),
                ('display_order', models.IntegerField(default=0)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='documents.document')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-saved_at', '-pk'),
            },
        ),
    ]
