# Generated by Django 5.2.14 on 2026-06-23 06:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0032_magicloginlink_expires_at_magicloginlink_multi_use'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The function's full name, used as the table column header (e.g. 'Application Interviews').", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe key; used in linkable directory filters (?function=application-interviews).', max_length=100, unique=True)),
                ('short_label', models.CharField(blank=True, help_text='Optional compact header for narrow table columns. Falls back to the name when blank.', max_length=40)),
                ('description', models.TextField(blank=True, help_text='Optional explanation shown to members alongside the function.')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers sort first in the table and filters.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive functions are hidden from members and the console but keep their history.')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=8)),
                ('start_date', models.DateField(help_text='The day this status took effect.')),
                ('end_date', models.DateField(blank=True, help_text='The day this status ended. Null means it is the current status (the open span).', null=True)),
                ('note', models.CharField(blank=True, help_text="Function-specific qualifier, verbatim from the sheet where given (e.g. 'Interviews OK Sept 2026', 'Except Oct-Dec 2026').", max_length=200)),
                ('source', models.CharField(choices=[('import', 'Imported from the yearly sheet'), ('coordinator', 'Set by the Applications Coordinator'), ('self', 'Set by the analyst'), ('admin', 'Set in the Django admin')], default='admin', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, help_text='Who recorded this span (null for an import or system action).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spans', to='availability.analystfunction')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_spans', to='accounts.profile')),
            ],
            options={
                'ordering': ['profile', 'function', '-start_date'],
                'indexes': [models.Index(fields=['function', 'status', 'end_date'], name='availabilit_functio_7c0e6b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('profile', 'function'), name='availability_one_open_span_per_profile_function')],
            },
        ),
    ]
