# Generated by Django 5.2.14 on 2026-06-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_seed_functions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_mode', models.CharField(choices=[('auto', 'Automatic'), ('review', 'Review first')], default='review', help_text='Automatic sends the periodic reminder on its own; review first leaves it for you to send from the console.', max_length=10, verbose_name='Availability reminders')),
            ],
            options={
                'verbose_name': 'Availability settings',
                'verbose_name_plural': 'Availability settings',
            },
        ),
        migrations.CreateModel(
            name='ReminderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('review_request', 'Please review your availability')], max_length=30, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
    ]
