# Generated by Django 5.2.14 on 2026-06-23 18:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_magicloginlink_expires_at_magicloginlink_multi_use'),
        ('availability', '0003_availabilitysettings_remindertemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityspan',
            name='note',
        ),
        migrations.AddField(
            model_name='availabilitysettings',
            name='last_auto_reminder_ay',
            field=models.CharField(blank=True, default='', help_text="The academic-year label the automatic reminder last fired for (e.g. '2026-2027'), so it sends at most once per year.", max_length=9),
        ),
        migrations.AlterField(
            model_name='availabilitysettings',
            name='reminder_mode',
            field=models.CharField(choices=[('auto', 'Automatic'), ('review', 'Review first')], default='review', help_text='Automatic: once at the start of each academic year (Sept 1) every analyst is emailed a review request. Review first: nothing is sent on its own — use the button on the Availability tab.', max_length=10, verbose_name='Availability reminders'),
        ),
        migrations.CreateModel(
            name='AvailabilityNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, help_text='Who wrote this note (null for an import).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_notes', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
