# Generated by Django 5.2.14 on 2026-05-31 21:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cartel",
            name="closed",
            field=models.BooleanField(
                default=False, help_text="Closed to new members (members may toggle)."
            ),
        ),
        migrations.AddField(
            model_name="cartel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 5, 31, 21, 16, 4, 724615, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartel",
            name="generator",
            field=models.ForeignKey(
                blank=True,
                help_text="The member who proposed the cartel.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cartels_generated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cartel",
            name="guiding_question",
            field=models.TextField(
                blank=True, help_text="The question the cartel forms around."
            ),
        ),
        migrations.AddField(
            model_name="cartel",
            name="review_note",
            field=models.TextField(
                blank=True, help_text="Decline reason / review notes."
            ),
        ),
        migrations.AddField(
            model_name="cartel",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartel",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The Cartel Coordinator who approved / declined.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cartels_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cartel",
            name="status",
            field=models.CharField(
                choices=[
                    ("proposed", "Proposed — awaiting Coordinator review"),
                    ("open", "Open — soliciting membership"),
                    ("declined", "Declined"),
                ],
                default="proposed",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="CartelInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cartel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="cartels.cartel",
                    ),
                ),
                (
                    "invited_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartel_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cartel", "invited_user"),
                        name="cartels_one_invitation_per_user",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CartelJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartel_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cartel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="cartels.cartel",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cartel_join_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("cartel", "applicant"),
                        name="cartels_one_pending_request_per_user",
                    )
                ],
            },
        ),
    ]
