# Generated by Django 5.2.14 on 2026-05-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartels", "0002_cartel_closed_cartel_created_at_cartel_generator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carteljoinrequest",
            name="message",
            field=models.TextField(
                blank=True,
                help_text="Why the applicant would like to join (shown to members).",
            ),
        ),
        migrations.AlterField(
            model_name="cartel",
            name="status",
            field=models.CharField(
                choices=[
                    ("proposed", "Proposed — awaiting Coordinator review"),
                    ("open", "Open — soliciting membership"),
                    ("declined", "Declined"),
                    ("archived", "Archived"),
                ],
                default="proposed",
                max_length=12,
            ),
        ),
    ]
