# Generated by Django 5.2.14 on 2026-05-31 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartels", "0003_carteljoinrequest_message_alter_cartel_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalPlusOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("affiliation", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Used to invite account creation.",
                        max_length=254,
                    ),
                ),
                ("invited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cartel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_plus_ones",
                        to="cartels.cartel",
                    ),
                ),
            ],
        ),
    ]
