# Generated by Django 5.2.14 on 2026-06-01 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartels", "0004_externalplusone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cartel",
            name="coordinator_feedback",
            field=models.TextField(
                blank=True,
                help_text="Cartel Coordinator's feedback / advocacy (advisory — the Program Committee approves).",
            ),
        ),
        migrations.AlterField(
            model_name="cartel",
            name="review_note",
            field=models.TextField(
                blank=True, help_text="Decline reason / PC review notes."
            ),
        ),
        migrations.AlterField(
            model_name="cartel",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The Program Committee member who approved / declined.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cartels_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
