# Generated by Django 5.2.14 on 2026-07-08 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartels', '0007_drop_legacy_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartel',
            name='registration_status',
            field=models.CharField(choices=[('forming', 'Forming — gathering members'), ('submitted', 'Submitted for PC registration'), ('registered', 'Registered — approved by the PC')], default='forming', help_text='Where the cartel sits in the formation → PC-registration flow.', max_length=10),
        ),
        migrations.CreateModel(
            name='CartelQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cartel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_questions', to='cartels.cartel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartel_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cartel', 'member'), name='cartels_one_question_per_member')],
            },
        ),
    ]
