# Generated by Django 5.2.14 on 2026-05-31 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workgroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cartel", "Cartel"),
                            ("working_group", "Working group"),
                            ("committee", "Committee"),
                            ("seminar", "Seminar"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Markdown supported."),
                ),
                (
                    "landing_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public — anyone"),
                            ("members", "Members — any LSP member"),
                            ("private", "Private — this group's members only"),
                        ],
                        default="members",
                        help_text="Who can see that this group exists (its landing page).",
                        max_length=16,
                    ),
                ),
                (
                    "content_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public — anyone"),
                            ("members", "Members — any LSP member"),
                            ("private", "Private — this group's members only"),
                        ],
                        default="private",
                        help_text="Who can see the roster, works, and files. Cannot be more public than the landing visibility.",
                        max_length=16,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Null for standing / ongoing groups.",
                        null=True,
                    ),
                ),
                ("has_channel", models.BooleanField(default=True)),
                ("has_works", models.BooleanField(default=True)),
                ("has_files", models.BooleanField(default=True)),
                ("has_calendar", models.BooleanField(default=False)),
                ("has_minutes", models.BooleanField(default=False)),
                ("has_tasks", models.BooleanField(default=False)),
                ("has_decisions", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional parent group (e.g. a committee that spawned this).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="workgroups.workgroup",
                    ),
                ),
            ],
            options={
                "ordering": ("kind", "name"),
            },
        ),
        migrations.CreateModel(
            name="WorkgroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("chair", "Chair"),
                            ("co_chair", "Co-chair"),
                            ("secretary", "Secretary"),
                            ("treasurer", "Treasurer"),
                            ("plus_one", "Plus-one"),
                            ("referral_coordinator", "Referral Coordinator"),
                            ("web_coordinator", "Web Coordinator"),
                            ("admin_assistant", "Admin Assistant"),
                        ],
                        default="member",
                        max_length=24,
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Null for currently-serving members.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workgroup_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="workgroups.workgroup",
                    ),
                ),
            ],
            options={
                "ordering": ("workgroup__name", "-start_date"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("end_date__isnull", True)),
                        fields=("user", "workgroup"),
                        name="workgroups_one_active_membership_per_user_group",
                    )
                ],
            },
        ),
    ]
