# Generated by Django 5.2.14 on 2026-05-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workgroups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workgroup",
            name="kind",
            field=models.CharField(
                choices=[
                    ("cartel", "Cartel"),
                    ("working_group", "Working group"),
                    ("committee", "Committee"),
                    ("seminar", "Seminar"),
                    ("reading_group", "Reading group"),
                ],
                max_length=16,
            ),
        ),
    ]
