# Generated by Django 5.2.14 on 2026-06-01 01:42

from django.conf import settings
from django.db import migrations, models


def copy_assignee_to_assignees(apps, schema_editor):
    """Preserve existing single-assignee data when moving to M2M."""
    WorkgroupTask = apps.get_model("workgroups", "WorkgroupTask")
    for task in WorkgroupTask.objects.exclude(assignee__isnull=True):
        task.assignees.add(task.assignee_id)


class Migration(migrations.Migration):

    dependencies = [
        ("workgroups", "0004_workgroupmeeting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workgrouptask",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_workgroup_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workgrouptask",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(copy_assignee_to_assignees, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="workgrouptask",
            name="assignee",
        ),
    ]
