# Generated by Django 5.2.14 on 2026-06-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workgroups", "0005_remove_workgrouptask_assignee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workgroupmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("chair", "Chair"),
                    ("co_chair", "Co-chair"),
                    ("secretary", "Secretary"),
                    ("treasurer", "Treasurer"),
                    ("plus_one", "Plus-one"),
                    ("faculty", "Faculty"),
                    ("referral_coordinator", "Referral Coordinator"),
                    ("web_coordinator", "Web Coordinator"),
                    ("admin_assistant", "Admin Assistant"),
                ],
                default="member",
                max_length=24,
            ),
        ),
    ]
