# Generated by Django 5.2.14 on 2026-06-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workgroups", "0006_alter_workgroupmembership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="workgroup",
            name="auto_member_role",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If set to a Profile role (e.g. 'analyst'), every active user with that role is automatically a member of this group — derived, no roster rows. Used for the Meeting of Analysts.",
                max_length=32,
            ),
        ),
    ]
