# Generated by Django 5.2.14 on 2026-06-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workgroups", "0007_workgroup_auto_member_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="workgroup",
            name="open_join",
            field=models.BooleanField(
                default=False,
                help_text="If set, any LSP member may join this group directly (one click, no approval or payment). Default for reading groups.",
            ),
        ),
        migrations.AlterField(
            model_name="workgroupmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("chair", "Chair"),
                    ("co_chair", "Co-chair"),
                    ("secretary", "Secretary"),
                    ("treasurer", "Treasurer"),
                    ("plus_one", "Plus-one"),
                    ("faculty", "Faculty"),
                    ("organizer", "Organizer"),
                    ("referral_coordinator", "Referral Coordinator"),
                    ("web_coordinator", "Web Coordinator"),
                    ("admin_assistant", "Admin Assistant"),
                ],
                default="member",
                max_length=24,
            ),
        ),
    ]
