# Generated by Django 5.2.14 on 2026-06-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workgroups", "0008_workgroupproposal_workgroupinvitation_and_more"),
        ("workgroups", "0011_freud_reading_group_paid_term"),
    ]

    operations = []
