# Generated by Django 5.2.14 on 2026-06-02 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workgroups", "0013_workgroup_archived_at_workgroup_archived_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workgroupmeeting",
            name="access_info",
            field=models.CharField(
                blank=True,
                help_text="Passcode / dial-in / access notes.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="workgroupmeeting",
            name="cancellation_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="workgroupmeeting",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workgroupmeeting",
            name="is_override",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workgroupmeeting",
            name="minutes",
            field=models.TextField(
                blank=True, help_text="Minutes / notes recorded after."
            ),
        ),
        migrations.AddField(
            model_name="workgroupmeeting",
            name="online_url",
            field=models.URLField(
                blank=True, help_text="Video-call link (Zoom, etc.)."
            ),
        ),
        migrations.AlterField(
            model_name="workgroupmeeting",
            name="location",
            field=models.CharField(
                blank=True, help_text="Room or short location.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="workgroupmeeting",
            name="note",
            field=models.TextField(blank=True, help_text="Agenda / description."),
        ),
        migrations.CreateModel(
            name="MeetingSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Every 2 weeks"),
                            ("monthly", "Monthly (nth weekday)"),
                        ],
                        default="weekly",
                        max_length=12,
                    ),
                ),
                ("weekdays", models.CharField(default="MO", max_length=32)),
                ("week_position", models.SmallIntegerField(default=1)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(help_text="The series runs through this date."),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("location", models.CharField(blank=True, max_length=255)),
                ("online_url", models.URLField(blank=True)),
                (
                    "access_info",
                    models.CharField(
                        blank=True,
                        help_text="Passcode / dial-in / room notes.",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_meeting_series",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_series",
                        to="workgroups.workgroup",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "meeting series",
                "ordering": ("-start_date",),
            },
        ),
        migrations.AddField(
            model_name="workgroupmeeting",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meetings",
                to="workgroups.meetingseries",
            ),
        ),
    ]
