# Generated by Django 5.2.14 on 2026-06-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workgroups", "0014_workgroupmeeting_access_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workgroup",
            name="has_terms",
            field=models.BooleanField(
                default=False,
                help_text="Track per-member term dates (start / end) in the roster. Defaulted on for committees, where officers serve defined terms.",
            ),
        ),
    ]
