# Generated by Django 5.2.14 on 2026-06-03 04:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workgroups", "0017_workgroup_file_quota_bytes_workgroupfile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkgroupDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="What was decided.", max_length=255),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True, help_text="Context / wording (markdown)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("adopted", "Adopted"),
                            ("rejected", "Rejected"),
                            ("tabled", "Tabled"),
                            ("superseded", "Superseded"),
                        ],
                        default="adopted",
                        max_length=12,
                    ),
                ),
                (
                    "decided_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        help_text="The meeting whose minutes recorded this decision, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions",
                        to="workgroups.workgroupmeeting",
                    ),
                ),
                (
                    "workgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="workgroups.workgroup",
                    ),
                ),
            ],
            options={
                "ordering": ("-decided_on", "-created_at"),
            },
        ),
    ]
