# Generated by Django 5.2.14 on 2026-06-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workgroups", "0018_workgroupdecision"),
    ]

    operations = [
        migrations.AddField(
            model_name="workgroup",
            name="recording_mode",
            field=models.CharField(
                choices=[
                    ("on_demand", "On demand — hosts can record"),
                    ("off", "Off — no Record button"),
                ],
                default="on_demand",
                help_text="Whether hosts see a Record button in this group's video meetings.",
                max_length=12,
            ),
        ),
    ]
