# Generated by Django 5.2.14 on 2026-06-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workgroups', '0020_meetingseries_week_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='meeting_reminders',
            field=models.BooleanField(default=True, help_text='Email members a reminder ~15 minutes before each scheduled meeting, with a personal one-tap join link.'),
        ),
        migrations.AddField(
            model_name='workgroupmeeting',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
