# Generated by Django 5.2.14 on 2026-06-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workgroups', '0021_workgroup_meeting_reminders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroupmembership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('chair', 'Chair'), ('co_chair', 'Co-chair'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('plus_one', 'Plus-one'), ('faculty', 'Faculty'), ('organizer', 'Organizer'), ('referral_coordinator', 'Referral Coordinator'), ('web_coordinator', 'Web Coordinator'), ('admin_assistant', 'Admin Assistant'), ('applications_coordinator', 'Applications Coordinator')], default='member', max_length=24),
        ),
    ]
