# Generated by Django 5.2.14 on 2026-06-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workgroups', '0022_alter_workgroupmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroupmembership',
            name='title',
            field=models.CharField(blank=True, help_text="Optional display title that overrides the role's default name — e.g. a Vice-President styled “Co-President”. The role stays the same; only the label shown on the site changes.", max_length=60),
        ),
        migrations.AlterField(
            model_name='workgroupmembership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('chair', 'Chair'), ('co_chair', 'Co-chair'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('plus_one', 'Plus-one'), ('faculty', 'Faculty'), ('organizer', 'Organizer'), ('president', 'President'), ('vice_president', 'Vice-President'), ('referral_coordinator', 'Referral Coordinator'), ('web_coordinator', 'Web Coordinator'), ('admin_assistant', 'Admin Assistant'), ('applications_coordinator', 'Applications Coordinator')], default='member', max_length=24),
        ),
    ]
