# Generated by Django 5.2.14 on 2026-06-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workgroups', '0023_workgroupmembership_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgroupmembership',
            name='title',
        ),
        migrations.AlterField(
            model_name='workgroupmembership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('chair', 'Chair'), ('co_chair', 'Co-chair'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('plus_one', 'Plus-one'), ('faculty', 'Faculty'), ('organizer', 'Organizer'), ('referral_coordinator', 'Referral Coordinator'), ('web_coordinator', 'Web Coordinator'), ('admin_assistant', 'Admin Assistant'), ('applications_coordinator', 'Applications Coordinator')], default='member', max_length=24),
        ),
    ]
