# Generated by Django 5.2.14 on 2026-07-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workgroups', '0024_remove_workgroupmembership_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingseries',
            name='timezone',
            field=models.CharField(default='America/Los_Angeles', help_text='IANA timezone the meeting times are anchored to.', max_length=64),
        ),
    ]
