# Generated by Django 5.2.14 on 2026-06-12 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Where this token lives, e.g. 'rico laptop — Claude Code'.", max_length=120)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('revoked', models.BooleanField(default=False, help_text='Revoked tokens are rejected without being deleted.')),
                ('user', models.ForeignKey(help_text='The token acts as this user; the API can do only what they can.', on_delete=django.db.models.deletion.CASCADE, related_name='devapi_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dev API token',
                'ordering': ('-created_at',),
            },
        ),
    ]
