# Generated by Django 5.2.14 on 2026-05-27 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quoted_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount due — resolved at registration time.",
                        max_digits=8,
                    ),
                ),
                (
                    "quoted_explanation",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable explanation of how quoted_amount was computed.",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_payment", "Awaiting payment"),
                            ("paid", "Paid"),
                            ("comped", "Comped"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="awaiting_payment",
                        max_length=20,
                    ),
                ),
                (
                    "staff_notes",
                    models.TextField(
                        blank=True, help_text="Manual override notes (REG-14)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
                (
                    "price_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="events.pricetier",
                    ),
                ),
                (
                    "pricing_code",
                    models.ForeignKey(
                        blank=True,
                        help_text="The code redeemed at registration time, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redemptions",
                        to="events.pricingcode",
                    ),
                ),
                (
                    "sessions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Set for per-class registration (REG-6); empty for whole-event.",
                        related_name="registrations",
                        to="events.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["event", "status"],
                        name="registratio_event_i_246b4a_idx",
                    ),
                    models.Index(
                        fields=["user", "event"], name="registratio_user_id_afd0d9_idx"
                    ),
                ],
            },
        ),
    ]
