# Generated by Django 5.2.14 on 2026-05-28 00:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_pricingcode_amount_or_percent"),
        ("registrations", "0002_cleanup_duplicate_active_registrations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("cancelled", "refunded")), _negated=True
                ),
                fields=("user", "event"),
                name="registrations_one_active_per_user_event",
            ),
        ),
    ]
