# Generated by Django 5.2.14 on 2026-06-01 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_event_requires_faculty_approval"),
        ("registrations", "0003_registration_registrations_one_active_per_user_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="registration",
            name="registrations_one_active_per_user_event",
        ),
        migrations.AddField(
            model_name="registration",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Faculty member who approved / declined this registration.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registration_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="decline_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="reminded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Pending faculty approval"),
                    ("awaiting_payment", "Awaiting payment"),
                    ("paid", "Paid"),
                    ("comped", "Comped"),
                    ("declined", "Declined by faculty"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="awaiting_payment",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("cancelled", "refunded", "declined")), _negated=True
                ),
                fields=("user", "event"),
                name="registrations_one_active_per_user_event",
            ),
        ),
    ]
