# Generated by Django 5.2.14 on 2026-05-31 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workgroups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkingGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workgroup",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_group",
                        to="workgroups.workgroup",
                    ),
                ),
            ],
        ),
    ]
