# Generated by Django 5.2.14 on 2026-06-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workgroups", "0018_workgroupdecision"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("url", models.URLField(max_length=500)),
                ("provider_created", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "workgroup",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_room",
                        to="workgroups.workgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily room",
            },
        ),
    ]
