# Generated by Django 5.2.14 on 2026-06-04 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parletre", "0014_alter_channel_kind"),
        ("video", "0001_initial"),
        ("workgroups", "0018_workgroupdecision"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyroom",
            name="channel",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_room",
                to="parletre.channel",
            ),
        ),
        migrations.AlterField(
            model_name="dailyroom",
            name="workgroup",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_room",
                to="workgroups.workgroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyroom",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("channel__isnull", True), ("workgroup__isnull", False)),
                    models.Q(("channel__isnull", False), ("workgroup__isnull", True)),
                    _connector="OR",
                ),
                name="video_room_exactly_one_owner",
            ),
        ),
    ]
