# Generated by Django 5.2.14 on 2026-06-05 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_event_record_video"),
        ("video", "0002_dailyroom_channel_alter_dailyroom_workgroup_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_recording_id", models.CharField(max_length=128, unique=True)),
                ("room_name", models.CharField(blank=True, max_length=128)),
                ("s3_key", models.CharField(blank=True, max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recording", "Recording"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                            ("deleted", "Deleted"),
                        ],
                        default="recording",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "listing_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("members", "Members (all LSP)"),
                            ("registrants", "Registrants only"),
                            ("group", "Group members only"),
                            ("staff", "Staff only (private)"),
                        ],
                        default="staff",
                        help_text="Who sees that this recording exists (e.g. on the event page).",
                        max_length=12,
                    ),
                ),
                (
                    "content_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("members", "Members (all LSP)"),
                            ("registrants", "Registrants only"),
                            ("group", "Group members only"),
                            ("staff", "Staff only (private)"),
                        ],
                        default="staff",
                        help_text="Who can watch it. Cannot be more public than the listing.",
                        max_length=12,
                    ),
                ),
                (
                    "keep",
                    models.BooleanField(
                        default=False,
                        help_text="Exempt from automatic retention deletion.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recordings",
                        to="events.event",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recordings",
                        to="video.dailyroom",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at", "-created_at"),
            },
        ),
    ]
