# Generated by Django 5.2.14 on 2026-06-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0003_recording"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="note",
            field=models.TextField(
                blank=True, help_text="Notes / annotation for this recording."
            ),
        ),
    ]
