# Generated by Django 5.2.14 on 2026-06-06 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_event_recording_mode"),
        ("parletre", "0018_the_gaze_no_recording"),
        ("video", "0004_recording_note"),
        ("workgroups", "0019_workgroup_recording_mode"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dailyroom",
            name="video_room_exactly_one_owner",
        ),
        migrations.AddField(
            model_name="dailyroom",
            name="event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_room",
                to="events.event",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyroom",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("channel__isnull", True),
                        ("event__isnull", True),
                        ("workgroup__isnull", False),
                    ),
                    models.Q(
                        ("channel__isnull", False),
                        ("event__isnull", True),
                        ("workgroup__isnull", True),
                    ),
                    models.Q(
                        ("channel__isnull", True),
                        ("event__isnull", False),
                        ("workgroup__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="video_room_exactly_one_owner",
            ),
        ),
    ]
