# Generated by Django 5.2.14 on 2026-08-29 09:06

import django.db.models.deletion
import video.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_online_venue_help_text'),
        ('parletre', '0018_the_gaze_no_recording'),
        ('video', '0006_recording_availability_levels'),
        ('workgroups', '0025_meetingseries_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=video.models._personal_slug, editable=False, max_length=64, unique=True)),
                ('recording_mode', models.CharField(choices=[('off', 'No recording'), ('on_demand', 'I can record')], default='off', help_text='Off by default, unlike every other room here: this room holds interviews and office hours, and a Record button does not belong in one unasked.', max_length=16)),
                ('office_hours', models.CharField(choices=[('off', 'Not shown'), ('posted', 'Posted hours, members may join'), ('appointment', 'By appointment only')], default='off', max_length=16)),
                ('hours_note', models.CharField(blank=True, help_text="Free text, e.g. 'Thursdays 3-4pm Pacific' or 'after seminar, or write to me'.", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'personal meeting room',
            },
        ),
        migrations.CreateModel(
            name='RoomInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('guest_name', models.CharField(blank=True, max_length=120)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('note', models.CharField(blank=True, help_text='Shown to the person you invited.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='dailyroom',
            name='video_room_exactly_one_owner',
        ),
        migrations.AddField(
            model_name='personalroom',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyroom',
            name='personal_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_room', to='video.personalroom'),
        ),
        migrations.AddConstraint(
            model_name='dailyroom',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('channel__isnull', True), ('event__isnull', True), ('personal_room__isnull', True), ('workgroup__isnull', False)), models.Q(('channel__isnull', False), ('event__isnull', True), ('personal_room__isnull', True), ('workgroup__isnull', True)), models.Q(('channel__isnull', True), ('event__isnull', False), ('personal_room__isnull', True), ('workgroup__isnull', True)), models.Q(('channel__isnull', True), ('event__isnull', True), ('personal_room__isnull', False), ('workgroup__isnull', True)), _connector='OR'), name='video_room_exactly_one_owner'),
        ),
        migrations.AddField(
            model_name='roominvitation',
            name='invited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roominvitation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='video.personalroom'),
        ),
        migrations.AddConstraint(
            model_name='roominvitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('invited_user__isnull', False), ('token__isnull', True)), models.Q(('invited_user__isnull', True), ('token__isnull', False)), _connector='OR'), name='video_invitation_exactly_one_kind'),
        ),
    ]
