# Generated by Django 5.2.14 on 2026-08-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_personalroom_roominvitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalroom',
            name='waiting_room',
            field=models.BooleanField(default=False, help_text='Hold arrivals on a waiting screen until you let them in, one at a time. Off by default: an invitation is already a decision about a person, so most meetings do not need to make it twice.'),
        ),
    ]
