# Generated by Django 5.2.14 on 2026-08-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_personalroom_waiting_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominvitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the invitation stops working. Blank means it lasts until revoked.', null=True),
        ),
    ]
