# Generated by Django 5.2.14 on 2026-06-05 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overrides", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("parletre_mention", "You're mentioned"),
                            ("parletre_reply", "Replies in your threads"),
                            ("parletre_thread", "New threads in channels you follow"),
                            ("registration_status", "Registration updates"),
                            ("registration_confirmed", "Registration confirmation"),
                            ("payment_receipt", "Payment receipts"),
                            ("dues_reminder", "Dues reminders"),
                            ("tuition_reminder", "Tuition reminders"),
                            ("cartel_invite", "Cartel invitations"),
                            ("cartel_application", "Cartel applications"),
                            ("cartel_decision", "Cartel decisions"),
                            ("cartel_proposal", "Cartel proposal review"),
                            ("admissions_application", "Admissions applications"),
                            ("admissions_decision", "Admissions decisions"),
                            ("admissions_advancement", "Advancement (demande)"),
                            ("group_membership", "Added to or removed from a group"),
                            ("group_meeting", "Group meetings scheduled"),
                            ("group_decision", "Group decisions & minutes"),
                            ("group_recording", "Meeting recordings ready"),
                            ("account_advisor", "Advisor assignments"),
                            ("account_security", "Account & security"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.CharField(blank=True, max_length=512)),
                ("url", models.CharField(blank=True, max_length=512)),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("emailed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at"],
                        name="notificatio_recipie_564b1f_idx",
                    ),
                    models.Index(
                        fields=["recipient", "category"],
                        name="notificatio_recipie_6bdf81_idx",
                    ),
                ],
            },
        ),
    ]
