# Generated by Django 5.2.14 on 2026-06-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_migrate_parletre_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="digest_pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="digest_cadence",
            field=models.CharField(
                choices=[("off", "Off"), ("daily", "Daily"), ("weekly", "Weekly")],
                default="weekly",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="last_digest_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
