# Generated by Django 5.2.14 on 2026-07-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('parletre_mention', "You're mentioned"), ('parletre_reply', 'Replies in your threads'), ('parletre_thread', 'New threads in channels you follow'), ('registration_status', 'Registration updates'), ('registration_confirmed', 'Registration confirmation'), ('payment_receipt', 'Payment receipts'), ('dues_reminder', 'Dues reminders'), ('tuition_reminder', 'Tuition reminders'), ('tuition_plan_review', 'Tuition payment plans'), ('balance_reminder', 'Balance reminders'), ('cartel_invite', 'Cartel invitations'), ('cartel_application', 'Cartel applications'), ('cartel_decision', 'Cartel decisions'), ('cartel_proposal', 'Cartel proposal review'), ('admissions_application', 'Admissions applications'), ('admissions_decision', 'Admissions decisions'), ('admissions_advancement', 'Advancement (demande)'), ('external_control_analyst', 'External control analyst review'), ('group_membership', 'Added to or removed from a group'), ('group_meeting', 'Group meetings scheduled'), ('group_meeting_reminder', 'Meeting starting soon'), ('group_decision', 'Group decisions & minutes'), ('group_recording', 'Meeting recordings ready'), ('event_change_review', 'Event content change reviews'), ('referral_request', 'Referral requests'), ('suggestion_filed', 'Suggestion review'), ('suggestion_update', 'Updates on your suggestions'), ('account_advisor', 'Advisor assignments'), ('account_updates', 'Account updates'), ('account_security', 'Account & security'), ('availability_review', 'Availability review requests')], max_length=32),
        ),
    ]
