# Generated by Django 5.2.14 on 2026-05-30 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("external", "External publication"),
                            ("cartel", "Cartel work"),
                            ("palimpsest", "Palimpsest"),
                            ("passage", "Passage"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "listing_visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("members", "Members only")],
                        default="public",
                        help_text="Who can see this work exists in the catalog.",
                        max_length=16,
                    ),
                ),
                (
                    "pdf_visibility",
                    models.CharField(
                        choices=[
                            ("none", "No PDF"),
                            ("public", "Public PDF"),
                            ("members", "Members-only PDF"),
                        ],
                        default="none",
                        help_text="Who can download the PDF. Cannot be more public than the listing — e.g. listing=Members blocks a Public PDF.",
                        max_length=16,
                    ),
                ),
                (
                    "abstract",
                    models.TextField(
                        blank=True, help_text="Short summary (markdown supported)."
                    ),
                ),
                (
                    "publication_info",
                    models.CharField(
                        blank=True,
                        help_text='Free-form citation, e.g. "Journal of X, Vol 12 (2024), pp. 33–58".',
                        max_length=255,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Link to publisher / DOI / external page."
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="works/pdf/%Y/"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="works/covers/%Y/"
                    ),
                ),
                (
                    "external_authors",
                    models.CharField(
                        blank=True,
                        help_text="Free-text co-authors not in our system (comma-separated).",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_works",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-publication_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="WorkAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorships",
                        to="works.work",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order",),
            },
        ),
        migrations.AddField(
            model_name="work",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="authored_works",
                through="works.WorkAuthor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="workauthor",
            constraint=models.UniqueConstraint(
                fields=("work", "user"), name="works_unique_author_per_work"
            ),
        ),
    ]
