# Generated by Django 5.2.14 on 2026-05-30 08:47

import django.db.models.deletion
from django.db import migrations, models


def move_pdf_to_workfile(apps, schema_editor):
    """For each Work with a `pdf` set, create one WorkFile carrying that
    file. Preserves the file path so storage points stay valid. Label is
    blank — the work has exactly one file so no label is required.
    """
    Work = apps.get_model("works", "Work")
    WorkFile = apps.get_model("works", "WorkFile")
    for w in Work.objects.exclude(pdf=""):
        if not w.pdf:
            continue
        WorkFile.objects.create(work=w, file=w.pdf.name, label="", display_order=0)


def normalize_pdf_visibility(apps, schema_editor):
    """Map legacy ``pdf_visibility='none'`` rows to 'members' (the new
    default). After this runs, the AlterField that drops the NONE
    choice is safe — no row carries an invalid value.
    """
    Work = apps.get_model("works", "Work")
    Work.objects.filter(pdf_visibility="none").update(pdf_visibility="members")


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0001_initial"),
    ]

    operations = [
        # 1. Stand up the WorkFile model.
        migrations.CreateModel(
            name="WorkFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="works/files/%Y/")),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Optional when this is the work's only file; required "
                            "when the work has multiple files."
                        ),
                        max_length=200,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="works.work",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "created_at"),
            },
        ),
        # 2. Move every Work.pdf payload into a WorkFile row.
        migrations.RunPython(
            move_pdf_to_workfile,
            reverse_code=migrations.RunPython.noop,
        ),
        # 3. Normalize any legacy "none" visibility values before we
        #    narrow the choice set.
        migrations.RunPython(
            normalize_pdf_visibility,
            reverse_code=migrations.RunPython.noop,
        ),
        # 4. Now the AlterField that drops the NONE choice is safe.
        migrations.AlterField(
            model_name="work",
            name="pdf_visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("members", "Members only")],
                default="members",
                help_text=(
                    "Who can download the PDFs attached to this work. Cannot "
                    "be more public than the listing — listing=Members blocks "
                    "a Public PDF setting."
                ),
                max_length=16,
            ),
        ),
        # 5. Finally drop the now-orphaned Work.pdf field.
        migrations.RemoveField(
            model_name="work",
            name="pdf",
        ),
    ]
