# Generated by Django 5.2.14 on 2026-05-31 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workgroups", "0001_initial"),
        ("works", "0002_remove_work_pdf_alter_work_pdf_visibility_workfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="workgroup",
            field=models.ForeignKey(
                blank=True,
                help_text="The producing group. Required when a visibility is set to 'Workgroup members only'.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="works",
                to="workgroups.workgroup",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="listing_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("members", "Members only"),
                    ("group", "Workgroup members only"),
                ],
                default="public",
                help_text="Who can see this work exists in the catalog.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="pdf_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("members", "Members only"),
                    ("group", "Workgroup members only"),
                ],
                default="members",
                help_text="Who can download the PDFs attached to this work. Cannot be more public than the listing — listing=Members blocks a Public PDF setting.",
                max_length=16,
            ),
        ),
    ]
