# Generated by Django 5.2.14 on 2026-05-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0003_work_workgroup_alter_work_listing_visibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="in_progress",
            field=models.BooleanField(
                default=False,
                help_text="Still being worked on (vs. released). Shown separately on the group's Work tab.",
            ),
        ),
    ]
