# Generated by Django 5.2.14 on 2026-06-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0007_rename_pdf_visibility_content_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="workdraft",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="If set, this is an uploaded file (e.g. a PDF) — a static working document, not edited in-app.",
                upload_to="workdrafts/%Y/",
            ),
        ),
    ]
