# Generated by Django 5.2.14 on 2026-06-03 03:04

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0008_workdraft_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workdraft",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="If set, this is an uploaded file (e.g. a PDF) — a static working document, not edited in-app.",
                storage=core.storage.private_storage,
                upload_to="workdrafts/%Y/",
            ),
        ),
        migrations.AlterField(
            model_name="workfile",
            name="file",
            field=models.FileField(
                storage=core.storage.private_storage, upload_to="works/files/%Y/"
            ),
        ),
    ]
