# Generated by Django 5.2.14 on 2026-06-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0009_alter_workdraft_file_alter_workfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="kind",
            field=models.CharField(
                choices=[
                    ("external", "External publication"),
                    ("cartel", "Cartel work"),
                    ("palimpsest", "Palimpsest"),
                    ("passage", "Passage"),
                    ("traversee", "Traversée"),
                    ("document", "Document"),
                ],
                max_length=16,
            ),
        ),
    ]
