# Generated by Django 5.2.14 on 2026-06-15 07:59

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_alter_work_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUploadSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Allow members to upload video to their works.')),
                ('max_file_mb', models.PositiveIntegerField(default=1024, help_text='Maximum size per video file, in megabytes (cost control).')),
            ],
            options={
                'verbose_name': 'Video upload settings',
                'verbose_name_plural': 'Video upload settings',
            },
        ),
        migrations.AddField(
            model_name='work',
            name='video',
            field=models.FileField(blank=True, help_text='Audio/video file (mp4, webm, or mov). Streamed to members who can open the contents.', storage=core.storage.private_storage, upload_to='works/videos/%Y/'),
        ),
    ]
