# Generated by Django 5.2.14 on 2026-07-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0011_videouploadsettings_work_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='content_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('members', 'Members only'), ('group', 'Workgroup members only')], default='members', help_text='Who can access the contents — the attached PDFs, the published HTML body, and any video. Cannot be more public than the listing — listing=Members blocks a Public contents setting.', max_length=16),
        ),
    ]
