# Generated by Django 5.2.14 on 2026-07-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_alter_work_content_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='container_title',
            field=models.CharField(blank=True, help_text="Journal name, or the book's title for a chapter.", max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='doi',
            field=models.CharField(blank=True, help_text='Bare DOI, e.g. "10.1234/xyz". A pasted doi.org URL is accepted.', max_length=255, verbose_name='DOI'),
        ),
        migrations.AddField(
            model_name='work',
            name='edition',
            field=models.CharField(blank=True, help_text='E.g. "2nd ed."', max_length=50),
        ),
        migrations.AddField(
            model_name='work',
            name='editors',
            field=models.CharField(blank=True, help_text='Names only, e.g. "Jane Doe and John Roe".', max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='external_type',
            field=models.CharField(blank=True, choices=[('article', 'Journal article'), ('book', 'Book'), ('chapter', 'Book chapter'), ('edited_volume', 'Edited volume'), ('other', 'Other')], default='', max_length=16, verbose_name='publication type'),
        ),
        migrations.AddField(
            model_name='work',
            name='isbn',
            field=models.CharField(blank=True, max_length=32, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='work',
            name='issue',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='work',
            name='pages',
            field=models.CharField(blank=True, help_text='E.g. "33–58".', max_length=50),
        ),
        migrations.AddField(
            model_name='work',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='translators',
            field=models.CharField(blank=True, help_text='Names only.', max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='volume',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
